# -*- coding: utf-8 -*-
"""Role-intelligence wording, in the six languages the app answers in.

Kept beside the other sentence tables rather than in the frontend, because this
is advisory prose rather than interface chrome: it belongs where every other
sentence WeatherGPT speaks is translated, so the two can never drift.

Same discipline as the rest of the corpus — fixed templates with numeric slots
filled from measured values, so the offline path stays multilingual and stays
incapable of inventing a number. The register is deliberately advisory:
"consider", "monitor", "may", never "must".
"""

from __future__ import annotations

ROLE_SENTENCES: dict[str, dict[str, str]] = {
    # -----------------------------------------------------------------------
    "en": {
        "ri_heading_general": "Everyday weather intelligence",
        "ri_heading_farmer": "Farm intelligence",
        "ri_heading_fisherman": "Marine intelligence",
        "ri_heading_traveler": "Travel intelligence",
        "ri_heading_commuter": "Commute intelligence",
        "ri_no_data": "Data unavailable",
        "ri_note_marine": "Wave, swell and tide data are not available in this app. This reading uses wind, storm and visibility from the weather forecast.",
        "ri_from_risk": "Based on the current {level} risk from {hazard}.",
        # General
        "ri_umbrella_title": "Umbrella",
        "ri_umbrella_yes": "Umbrella recommended",
        "ri_umbrella_maybe": "Worth carrying one",
        "ri_umbrella_no": "Umbrella not necessary",
        "ri_umbrella_prob": "Rain chance peaks near {prob}% in the next 12 hours.",
        "ri_umbrella_mm": "About {mm} mm of rain is expected over 24 hours.",
        "ri_comfort_title": "Comfort",
        "ri_comfort_hot": "Hot — stay hydrated",
        "ri_comfort_muggy": "Warm and humid",
        "ri_comfort_warm": "Warm",
        "ri_comfort_cool": "Cool",
        "ri_comfort_ok": "Comfortable",
        "ri_comfort_detail": "Feels like {feels}°C at {hum}% humidity.",
        "ri_comfort_detail_temp": "Feels like {feels}°C.",
        "ri_outdoor_title": "Outdoors",
        "ri_outdoor_avoid": "Avoid prolonged outdoor activity",
        "ri_outdoor_caution": "Outdoor activity with caution",
        "ri_outdoor_good": "Good for outdoor activity",
        # Farmer
        "ri_rain_title": "Rain impact",
        "ri_rain_high": "High",
        "ri_rain_moderate": "Moderate",
        "ri_rain_low": "Low",
        "ri_rain_detail_mm": "About {mm} mm is expected over the next 24 hours.",
        "ri_rain_detail_prob": "Rain chance peaks near {prob}% in the next 12 hours.",
        "ri_irrigation_title": "Irrigation advisor",
        "ri_irrigation_nodata": "Insufficient rainfall data for an irrigation recommendation",
        "ri_irrigation_delay": "Consider delaying irrigation",
        "ri_irrigation_delay_detail": "About {mm} mm of rain is expected over the next 24 hours.",
        "ri_irrigation_needed": "Irrigation may be needed",
        "ri_irrigation_dry_detail": "Little or no rain is expected in the forecast period.",
        "ri_irrigation_monitor": "Monitor conditions",
        "ri_irrigation_monitor_detail": "About {mm} mm is expected — light, and may not be enough.",
        "ri_crop_title": "Crop weather risk",
        "ri_crop_high": "High",
        "ri_crop_moderate": "Moderate",
        "ri_crop_low": "Low",
        "ri_crop_high_detail": "Warm, wet air at {hum}% humidity is the kind of weather in which fungal problems become more likely. Consider checking crops after rainfall.",
        "ri_crop_moderate_detail": "Humidity is {hum}%. Monitoring after rainfall may be useful.",
        "ri_crop_low_detail": "Humidity is {hum}% — drier than the range that usually raises concern.",
        "ri_field_title": "Today's field advisory",
        "ri_field_storm": "Thunderstorm conditions are possible. Consider postponing field work and securing equipment.",
        "ri_field_rain": "About {mm} mm of rain is expected. Consider checking field moisture before irrigating.",
        "ri_field_humid": "Humidity is high at {hum}%. Monitoring crops for moisture-related problems may be useful.",
        "ri_field_hot": "It will feel around {feels}°C. Consider checking soil moisture and watering early or late in the day.",
        "ri_field_clear": "No significant weather is expected. A usable window for field work.",
        # Fisherman
        "ri_fishing_title": "Fishing conditions",
        "ri_fishing_avoid": "Avoid",
        "ri_fishing_caution": "Caution",
        "ri_fishing_favorable": "Favorable",
        "ri_fishing_detail": "Weather-based only. Check official marine warnings before going out.",
        "ri_wind_title": "Wind",
        "ri_wind_gust": "Gusting to about {gust} km/h.",
        "ri_storm_title": "Lightning and storm risk",
        "ri_storm_high": "High",
        "ri_storm_moderate": "Moderate",
        "ri_storm_low": "Low",
        "ri_storm_high_detail": "Thunderstorm activity is likely. Monitor official warnings before heading out.",
        "ri_storm_moderate_detail": "Thunderstorm activity is possible. Monitor official warnings before heading out.",
        "ri_storm_low_detail": "No thunderstorm activity is indicated right now.",
        "ri_visibility_title": "Visibility",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "rain",
        "ri_factor_visibility": "low visibility",
        "ri_factor_wind": "strong wind",
        "ri_factor_storm": "thunderstorm",
        # Traveller
        "ri_trip_title": "Trip weather",
        "ri_trip_tomorrow": "Tomorrow: about {prob}% chance of rain.",
        "ri_trip_tomorrow_cond": "Tomorrow: {cond}.",
        "ri_travel_title": "Travel risk",
        "ri_travel_high": "High",
        "ri_travel_moderate": "Moderate",
        "ri_travel_low": "Low",
        "ri_travel_factors": "Contributing: {factors}.",
        "ri_travel_clear": "No weather factor is working against travel right now.",
        "ri_activity_title": "Outdoor activity",
        "ri_activity_poor": "Poor",
        "ri_activity_caution": "Use caution",
        "ri_activity_good": "Good",
        "ri_activity_excellent": "Excellent",
        "ri_pack_title": "Packing assistant",
        "ri_pack_umbrella": "Umbrella",
        "ri_pack_raincoat": "Rain jacket",
        "ri_pack_water": "Water",
        "ri_pack_sun": "Sun protection",
        "ri_pack_layer": "Warm layer",
        "ri_pack_windproof": "Windproof layer",
        "ri_pack_nothing": "Nothing weather-specific needed",
        # Commuter
        "ri_commute_title": "Commute risk",
        "ri_commute_high": "High",
        "ri_commute_moderate": "Moderate",
        "ri_commute_low": "Low",
        "ri_commute_detail": "Weather risk only — this does not include traffic.",
        "ri_hazards_title": "Weather hazards",
        "ri_hazards_none": "None detected",
        "ri_departure_title": "Calmest departure",
        "ri_departure_detail": "Lowest weather risk in the next commute window.",
        "ri_reminder_title": "Reminder",
        "ri_reminder_storm": "Storm conditions are possible — consider allowing extra time.",
        "ri_reminder_rain": "Carry an umbrella and allow a little extra time.",
        "ri_reminder_wind": "Strong wind is expected — take care on exposed roads.",
        "ri_reminder_clear": "Weather conditions look favorable for your commute.",
    },
    # -----------------------------------------------------------------------
    "hi": {
        "ri_heading_general": "रोज़मर्रा की मौसम जानकारी",
        "ri_heading_farmer": "खेती की मौसम जानकारी",
        "ri_heading_fisherman": "समुद्री मौसम जानकारी",
        "ri_heading_traveler": "यात्रा की मौसम जानकारी",
        "ri_heading_commuter": "आवाजाही की मौसम जानकारी",
        "ri_no_data": "जानकारी उपलब्ध नहीं",
        "ri_note_marine": "इस ऐप में लहर, स्वेल और ज्वार-भाटा की जानकारी उपलब्ध नहीं है। यह आकलन मौसम पूर्वानुमान की हवा, तूफ़ान और दृश्यता पर आधारित है।",
        "ri_from_risk": "{hazard} से मौजूदा {level} जोखिम के आधार पर।",
        "ri_umbrella_title": "छाता",
        "ri_umbrella_yes": "छाता साथ रखें",
        "ri_umbrella_maybe": "छाता रखना बेहतर होगा",
        "ri_umbrella_no": "छाते की ज़रूरत नहीं",
        "ri_umbrella_prob": "अगले 12 घंटों में बारिश की संभावना लगभग {prob}% तक पहुँचती है।",
        "ri_umbrella_mm": "24 घंटों में लगभग {mm} मिमी बारिश का अनुमान है।",
        "ri_comfort_title": "आराम",
        "ri_comfort_hot": "गर्मी — पानी पीते रहें",
        "ri_comfort_muggy": "गर्म और उमस भरा",
        "ri_comfort_warm": "गर्म",
        "ri_comfort_cool": "ठंडा",
        "ri_comfort_ok": "आरामदायक",
        "ri_comfort_detail": "{hum}% नमी के साथ {feels}°C जैसा महसूस होता है।",
        "ri_comfort_detail_temp": "{feels}°C जैसा महसूस होता है।",
        "ri_outdoor_title": "बाहर निकलना",
        "ri_outdoor_avoid": "लंबे समय तक बाहर रहने से बचें",
        "ri_outdoor_caution": "सावधानी के साथ बाहर जाएँ",
        "ri_outdoor_good": "बाहर जाने के लिए अच्छा समय",
        "ri_rain_title": "बारिश का असर",
        "ri_rain_high": "अधिक",
        "ri_rain_moderate": "मध्यम",
        "ri_rain_low": "कम",
        "ri_rain_detail_mm": "अगले 24 घंटों में लगभग {mm} मिमी का अनुमान है।",
        "ri_rain_detail_prob": "अगले 12 घंटों में बारिश की संभावना लगभग {prob}% तक पहुँचती है।",
        "ri_irrigation_title": "सिंचाई सलाह",
        "ri_irrigation_nodata": "सिंचाई की सलाह के लिए वर्षा के पर्याप्त आँकड़े नहीं हैं",
        "ri_irrigation_delay": "सिंचाई टालने पर विचार करें",
        "ri_irrigation_delay_detail": "अगले 24 घंटों में लगभग {mm} मिमी बारिश का अनुमान है।",
        "ri_irrigation_needed": "सिंचाई की ज़रूरत हो सकती है",
        "ri_irrigation_dry_detail": "पूर्वानुमान अवधि में बहुत कम या कोई बारिश नहीं दिख रही।",
        "ri_irrigation_monitor": "स्थिति पर नज़र रखें",
        "ri_irrigation_monitor_detail": "लगभग {mm} मिमी का अनुमान है — हल्की, शायद पर्याप्त न हो।",
        "ri_crop_title": "फ़सल पर मौसम का जोखिम",
        "ri_crop_high": "अधिक",
        "ri_crop_moderate": "मध्यम",
        "ri_crop_low": "कम",
        "ri_crop_high_detail": "{hum}% नमी वाला गर्म और गीला मौसम वह स्थिति है जिसमें फफूँद की समस्या की संभावना बढ़ जाती है। बारिश के बाद फ़सल देखने पर विचार करें।",
        "ri_crop_moderate_detail": "नमी {hum}% है। बारिश के बाद निगरानी उपयोगी हो सकती है।",
        "ri_crop_low_detail": "नमी {hum}% है — उस सीमा से कम जो आमतौर पर चिंता बढ़ाती है।",
        "ri_field_title": "आज की खेत सलाह",
        "ri_field_storm": "आँधी-तूफ़ान की स्थिति संभव है। खेत का काम टालने और उपकरण सुरक्षित रखने पर विचार करें।",
        "ri_field_rain": "लगभग {mm} मिमी बारिश का अनुमान है। सिंचाई से पहले खेत की नमी देखने पर विचार करें।",
        "ri_field_humid": "नमी {hum}% के साथ अधिक है। नमी से जुड़ी समस्याओं के लिए फ़सल की निगरानी उपयोगी हो सकती है।",
        "ri_field_hot": "लगभग {feels}°C जैसा महसूस होगा। मिट्टी की नमी देखने और सुबह या शाम पानी देने पर विचार करें।",
        "ri_field_clear": "कोई बड़ा मौसम बदलाव नहीं दिख रहा। खेत के काम के लिए उपयुक्त समय।",
        "ri_fishing_title": "मछली पकड़ने की स्थिति",
        "ri_fishing_avoid": "टालें",
        "ri_fishing_caution": "सावधानी",
        "ri_fishing_favorable": "अनुकूल",
        "ri_fishing_detail": "केवल मौसम के आधार पर। निकलने से पहले आधिकारिक समुद्री चेतावनी देखें।",
        "ri_wind_title": "हवा",
        "ri_wind_gust": "झोंके लगभग {gust} किमी/घंटा तक।",
        "ri_storm_title": "बिजली और तूफ़ान का जोखिम",
        "ri_storm_high": "अधिक",
        "ri_storm_moderate": "मध्यम",
        "ri_storm_low": "कम",
        "ri_storm_high_detail": "गरज के साथ तूफ़ान की संभावना है। निकलने से पहले आधिकारिक चेतावनी देखें।",
        "ri_storm_moderate_detail": "गरज के साथ तूफ़ान संभव है। निकलने से पहले आधिकारिक चेतावनी देखें।",
        "ri_storm_low_detail": "फ़िलहाल तूफ़ान का कोई संकेत नहीं है।",
        "ri_visibility_title": "दृश्यता",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "बारिश",
        "ri_factor_visibility": "कम दृश्यता",
        "ri_factor_wind": "तेज़ हवा",
        "ri_factor_storm": "तूफ़ान",
        "ri_trip_title": "यात्रा का मौसम",
        "ri_trip_tomorrow": "कल: बारिश की संभावना लगभग {prob}%।",
        "ri_trip_tomorrow_cond": "कल: {cond}।",
        "ri_travel_title": "यात्रा जोखिम",
        "ri_travel_high": "अधिक",
        "ri_travel_moderate": "मध्यम",
        "ri_travel_low": "कम",
        "ri_travel_factors": "कारण: {factors}।",
        "ri_travel_clear": "अभी कोई मौसम कारण यात्रा के विरुद्ध नहीं है।",
        "ri_activity_title": "बाहरी गतिविधि",
        "ri_activity_poor": "ख़राब",
        "ri_activity_caution": "सावधानी बरतें",
        "ri_activity_good": "ठीक",
        "ri_activity_excellent": "बहुत अच्छा",
        "ri_pack_title": "सामान की सलाह",
        "ri_pack_umbrella": "छाता",
        "ri_pack_raincoat": "बरसाती",
        "ri_pack_water": "पानी",
        "ri_pack_sun": "धूप से बचाव",
        "ri_pack_layer": "गर्म कपड़े",
        "ri_pack_windproof": "हवा रोकने वाली परत",
        "ri_pack_nothing": "मौसम के लिए कुछ ख़ास ज़रूरी नहीं",
        "ri_commute_title": "आवाजाही जोखिम",
        "ri_commute_high": "अधिक",
        "ri_commute_moderate": "मध्यम",
        "ri_commute_low": "कम",
        "ri_commute_detail": "केवल मौसम का जोखिम — इसमें यातायात शामिल नहीं है।",
        "ri_hazards_title": "मौसम ख़तरे",
        "ri_hazards_none": "कोई नहीं मिला",
        "ri_departure_title": "सबसे शांत समय",
        "ri_departure_detail": "अगली आवाजाही अवधि में सबसे कम मौसम जोखिम।",
        "ri_reminder_title": "याद रखें",
        "ri_reminder_storm": "तूफ़ान की स्थिति संभव है — कुछ अतिरिक्त समय रखें।",
        "ri_reminder_rain": "छाता साथ रखें और थोड़ा अतिरिक्त समय लेकर चलें।",
        "ri_reminder_wind": "तेज़ हवा का अनुमान है — खुली सड़कों पर सावधानी रखें।",
        "ri_reminder_clear": "आपकी आवाजाही के लिए मौसम अनुकूल दिख रहा है।",
    },
    # -----------------------------------------------------------------------
    "te": {
        "ri_heading_general": "రోజువారీ వాతావరణ సమాచారం",
        "ri_heading_farmer": "వ్యవసాయ వాతావరణ సమాచారం",
        "ri_heading_fisherman": "సముద్ర వాతావరణ సమాచారం",
        "ri_heading_traveler": "ప్రయాణ వాతావరణ సమాచారం",
        "ri_heading_commuter": "ప్రయాణ మార్గ వాతావరణ సమాచారం",
        "ri_no_data": "సమాచారం అందుబాటులో లేదు",
        "ri_note_marine": "ఈ యాప్‌లో అలలు, స్వెల్ మరియు ఆటుపోట్ల సమాచారం అందుబాటులో లేదు. ఈ అంచనా వాతావరణ సూచనలోని గాలి, తుఫాను మరియు దృశ్యత ఆధారంగా ఉంది.",
        "ri_from_risk": "{hazard} నుండి ప్రస్తుత {level} ప్రమాదం ఆధారంగా.",
        "ri_umbrella_title": "గొడుగు",
        "ri_umbrella_yes": "గొడుగు తీసుకెళ్లండి",
        "ri_umbrella_maybe": "గొడుగు ఉంచుకోవడం మంచిది",
        "ri_umbrella_no": "గొడుగు అవసరం లేదు",
        "ri_umbrella_prob": "రాబోయే 12 గంటల్లో వర్ష సంభావ్యత సుమారు {prob}% వరకు ఉంటుంది.",
        "ri_umbrella_mm": "24 గంటల్లో సుమారు {mm} మి.మీ. వర్షం అంచనా.",
        "ri_comfort_title": "సౌకర్యం",
        "ri_comfort_hot": "వేడి — నీరు తాగుతూ ఉండండి",
        "ri_comfort_muggy": "వేడి మరియు తేమ",
        "ri_comfort_warm": "వెచ్చగా",
        "ri_comfort_cool": "చల్లగా",
        "ri_comfort_ok": "హాయిగా",
        "ri_comfort_detail": "{hum}% తేమతో {feels}°C లా అనిపిస్తుంది.",
        "ri_comfort_detail_temp": "{feels}°C లా అనిపిస్తుంది.",
        "ri_outdoor_title": "బయటికి వెళ్లడం",
        "ri_outdoor_avoid": "ఎక్కువసేపు బయట ఉండటం మానండి",
        "ri_outdoor_caution": "జాగ్రత్తగా బయటికి వెళ్లండి",
        "ri_outdoor_good": "బయటి పనులకు అనుకూలం",
        "ri_rain_title": "వర్ష ప్రభావం",
        "ri_rain_high": "ఎక్కువ",
        "ri_rain_moderate": "మధ్యస్థం",
        "ri_rain_low": "తక్కువ",
        "ri_rain_detail_mm": "రాబోయే 24 గంటల్లో సుమారు {mm} మి.మీ. అంచనా.",
        "ri_rain_detail_prob": "రాబోయే 12 గంటల్లో వర్ష సంభావ్యత సుమారు {prob}% వరకు ఉంటుంది.",
        "ri_irrigation_title": "నీటిపారుదల సలహా",
        "ri_irrigation_nodata": "నీటిపారుదల సలహాకు తగినంత వర్ష సమాచారం లేదు",
        "ri_irrigation_delay": "నీటిపారుదల వాయిదా వేయడాన్ని పరిశీలించండి",
        "ri_irrigation_delay_detail": "రాబోయే 24 గంటల్లో సుమారు {mm} మి.మీ. వర్షం అంచనా.",
        "ri_irrigation_needed": "నీటిపారుదల అవసరం కావచ్చు",
        "ri_irrigation_dry_detail": "సూచన కాలంలో వర్షం చాలా తక్కువ లేదా లేదు.",
        "ri_irrigation_monitor": "పరిస్థితిని గమనించండి",
        "ri_irrigation_monitor_detail": "సుమారు {mm} మి.మీ. అంచనా — తేలికపాటిది, సరిపోకపోవచ్చు.",
        "ri_crop_title": "పంటలపై వాతావరణ ప్రమాదం",
        "ri_crop_high": "ఎక్కువ",
        "ri_crop_moderate": "మధ్యస్థం",
        "ri_crop_low": "తక్కువ",
        "ri_crop_high_detail": "{hum}% తేమతో కూడిన వెచ్చని, తడి గాలి శిలీంధ్ర సమస్యల అవకాశం పెరిగే వాతావరణం. వర్షం తర్వాత పంటలను చూడటాన్ని పరిశీలించండి.",
        "ri_crop_moderate_detail": "తేమ {hum}%. వర్షం తర్వాత గమనించడం ఉపయోగకరం కావచ్చు.",
        "ri_crop_low_detail": "తేమ {hum}% — సాధారణంగా ఆందోళన కలిగించే స్థాయి కంటే తక్కువ.",
        "ri_field_title": "నేటి పొలం సలహా",
        "ri_field_storm": "ఉరుములతో కూడిన తుఫాను అవకాశం ఉంది. పొలం పనులు వాయిదా వేసి, పరికరాలను భద్రపరచడాన్ని పరిశీలించండి.",
        "ri_field_rain": "సుమారు {mm} మి.మీ. వర్షం అంచనా. నీరు పెట్టే ముందు పొలంలో తేమను చూడటాన్ని పరిశీలించండి.",
        "ri_field_humid": "తేమ {hum}% తో ఎక్కువగా ఉంది. తేమ సంబంధిత సమస్యల కోసం పంటలను గమనించడం ఉపయోగకరం కావచ్చు.",
        "ri_field_hot": "సుమారు {feels}°C లా అనిపిస్తుంది. నేల తేమను చూసి, ఉదయం లేదా సాయంత్రం నీరు పెట్టడాన్ని పరిశీలించండి.",
        "ri_field_clear": "పెద్ద వాతావరణ మార్పు కనిపించడం లేదు. పొలం పనులకు అనుకూల సమయం.",
        "ri_fishing_title": "చేపల వేట పరిస్థితి",
        "ri_fishing_avoid": "వద్దు",
        "ri_fishing_caution": "జాగ్రత్త",
        "ri_fishing_favorable": "అనుకూలం",
        "ri_fishing_detail": "వాతావరణం ఆధారంగా మాత్రమే. బయలుదేరే ముందు అధికారిక సముద్ర హెచ్చరికలను చూడండి.",
        "ri_wind_title": "గాలి",
        "ri_wind_gust": "గాలి తాకిడి సుమారు {gust} కి.మీ./గం. వరకు.",
        "ri_storm_title": "పిడుగులు మరియు తుఫాను ప్రమాదం",
        "ri_storm_high": "ఎక్కువ",
        "ri_storm_moderate": "మధ్యస్థం",
        "ri_storm_low": "తక్కువ",
        "ri_storm_high_detail": "ఉరుములతో కూడిన తుఫాను అవకాశం ఎక్కువ. బయలుదేరే ముందు అధికారిక హెచ్చరికలను చూడండి.",
        "ri_storm_moderate_detail": "ఉరుములతో కూడిన తుఫాను సాధ్యం. బయలుదేరే ముందు అధికారిక హెచ్చరికలను చూడండి.",
        "ri_storm_low_detail": "ప్రస్తుతం తుఫాను సూచనలు లేవు.",
        "ri_visibility_title": "దృశ్యత",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "వర్షం",
        "ri_factor_visibility": "తక్కువ దృశ్యత",
        "ri_factor_wind": "బలమైన గాలి",
        "ri_factor_storm": "తుఫాను",
        "ri_trip_title": "ప్రయాణ వాతావరణం",
        "ri_trip_tomorrow": "రేపు: వర్ష సంభావ్యత సుమారు {prob}%.",
        "ri_trip_tomorrow_cond": "రేపు: {cond}.",
        "ri_travel_title": "ప్రయాణ ప్రమాదం",
        "ri_travel_high": "ఎక్కువ",
        "ri_travel_moderate": "మధ్యస్థం",
        "ri_travel_low": "తక్కువ",
        "ri_travel_factors": "కారణాలు: {factors}.",
        "ri_travel_clear": "ప్రస్తుతం ప్రయాణానికి వ్యతిరేకంగా ఏ వాతావరణ కారణం లేదు.",
        "ri_activity_title": "బయటి కార్యకలాపాలు",
        "ri_activity_poor": "అనుకూలం కాదు",
        "ri_activity_caution": "జాగ్రత్త అవసరం",
        "ri_activity_good": "బాగుంది",
        "ri_activity_excellent": "చాలా బాగుంది",
        "ri_pack_title": "సర్దుకోవాల్సినవి",
        "ri_pack_umbrella": "గొడుగు",
        "ri_pack_raincoat": "రेయిన్ జాకెట్",
        "ri_pack_water": "నీరు",
        "ri_pack_sun": "ఎండ నుండి రక్షణ",
        "ri_pack_layer": "వెచ్చని దుస్తులు",
        "ri_pack_windproof": "గాలిని ఆపే దుస్తులు",
        "ri_pack_nothing": "వాతావరణం కోసం ప్రత్యేకంగా ఏమీ అవసరం లేదు",
        "ri_commute_title": "ప్రయాణ మార్గ ప్రమాదం",
        "ri_commute_high": "ఎక్కువ",
        "ri_commute_moderate": "మధ్యస్థం",
        "ri_commute_low": "తక్కువ",
        "ri_commute_detail": "వాతావరణ ప్రమాదం మాత్రమే — ఇందులో ట్రాఫిక్ లేదు.",
        "ri_hazards_title": "వాతావరణ ప్రమాదాలు",
        "ri_hazards_none": "ఏవీ కనిపించలేదు",
        "ri_departure_title": "ప్రశాంతమైన సమయం",
        "ri_departure_detail": "రాబోయే ప్రయాణ సమయంలో అత్యల్ప వాతావరణ ప్రమాదం.",
        "ri_reminder_title": "గుర్తుంచుకోండి",
        "ri_reminder_storm": "తుఫాను పరిస్థితి సాధ్యం — కొంత అదనపు సమయం తీసుకోండి.",
        "ri_reminder_rain": "గొడుగు తీసుకెళ్లండి, కొంత అదనపు సమయం ఉంచుకోండి.",
        "ri_reminder_wind": "బలమైన గాలి అంచనా — బహిరంగ రహదారులపై జాగ్రత్త.",
        "ri_reminder_clear": "మీ ప్రయాణానికి వాతావరణం అనుకూలంగా ఉంది.",
    },
    # -----------------------------------------------------------------------
    "bn": {
        "ri_heading_general": "দৈনন্দিন আবহাওয়া তথ্য",
        "ri_heading_farmer": "কৃষি আবহাওয়া তথ্য",
        "ri_heading_fisherman": "সামুদ্রিক আবহাওয়া তথ্য",
        "ri_heading_traveler": "ভ্রমণ আবহাওয়া তথ্য",
        "ri_heading_commuter": "যাতায়াত আবহাওয়া তথ্য",
        "ri_no_data": "তথ্য পাওয়া যায়নি",
        "ri_note_marine": "এই অ্যাপে ঢেউ, স্বেল ও জোয়ার-ভাটার তথ্য নেই। এই মূল্যায়ন আবহাওয়া পূর্বাভাসের বাতাস, ঝড় ও দৃশ্যমানতার উপর ভিত্তি করে।",
        "ri_from_risk": "{hazard} থেকে বর্তমান {level} ঝুঁকির ভিত্তিতে।",
        "ri_umbrella_title": "ছাতা",
        "ri_umbrella_yes": "ছাতা নিন",
        "ri_umbrella_maybe": "ছাতা রাখা ভালো",
        "ri_umbrella_no": "ছাতার দরকার নেই",
        "ri_umbrella_prob": "আগামী 12 ঘণ্টায় বৃষ্টির সম্ভাবনা প্রায় {prob}% পর্যন্ত ওঠে।",
        "ri_umbrella_mm": "24 ঘণ্টায় প্রায় {mm} মিমি বৃষ্টি হতে পারে।",
        "ri_comfort_title": "স্বাচ্ছন্দ্য",
        "ri_comfort_hot": "গরম — পানি পান করতে থাকুন",
        "ri_comfort_muggy": "গরম ও আর্দ্র",
        "ri_comfort_warm": "গরম",
        "ri_comfort_cool": "ঠান্ডা",
        "ri_comfort_ok": "আরামদায়ক",
        "ri_comfort_detail": "{hum}% আর্দ্রতায় {feels}°C-এর মতো লাগে।",
        "ri_comfort_detail_temp": "{feels}°C-এর মতো লাগে।",
        "ri_outdoor_title": "বাইরে বেরোনো",
        "ri_outdoor_avoid": "দীর্ঘক্ষণ বাইরে থাকা এড়ান",
        "ri_outdoor_caution": "সতর্ক থেকে বাইরে যান",
        "ri_outdoor_good": "বাইরের কাজের জন্য ভালো",
        "ri_rain_title": "বৃষ্টির প্রভাব",
        "ri_rain_high": "বেশি",
        "ri_rain_moderate": "মাঝারি",
        "ri_rain_low": "কম",
        "ri_rain_detail_mm": "আগামী 24 ঘণ্টায় প্রায় {mm} মিমি হতে পারে।",
        "ri_rain_detail_prob": "আগামী 12 ঘণ্টায় বৃষ্টির সম্ভাবনা প্রায় {prob}% পর্যন্ত ওঠে।",
        "ri_irrigation_title": "সেচ পরামর্শ",
        "ri_irrigation_nodata": "সেচের পরামর্শের জন্য যথেষ্ট বৃষ্টির তথ্য নেই",
        "ri_irrigation_delay": "সেচ পিছিয়ে দেওয়ার কথা ভাবুন",
        "ri_irrigation_delay_detail": "আগামী 24 ঘণ্টায় প্রায় {mm} মিমি বৃষ্টি হতে পারে।",
        "ri_irrigation_needed": "সেচের দরকার হতে পারে",
        "ri_irrigation_dry_detail": "পূর্বাভাসের সময়ে বৃষ্টি খুব কম বা নেই।",
        "ri_irrigation_monitor": "পরিস্থিতির উপর নজর রাখুন",
        "ri_irrigation_monitor_detail": "প্রায় {mm} মিমি হতে পারে — হালকা, যথেষ্ট নাও হতে পারে।",
        "ri_crop_title": "ফসলে আবহাওয়ার ঝুঁকি",
        "ri_crop_high": "বেশি",
        "ri_crop_moderate": "মাঝারি",
        "ri_crop_low": "কম",
        "ri_crop_high_detail": "{hum}% আর্দ্রতাযুক্ত গরম, ভেজা বাতাস এমন আবহাওয়া যেখানে ছত্রাকজনিত সমস্যার সম্ভাবনা বাড়ে। বৃষ্টির পরে ফসল দেখার কথা ভাবুন।",
        "ri_crop_moderate_detail": "আর্দ্রতা {hum}%। বৃষ্টির পরে নজর রাখা কাজে লাগতে পারে।",
        "ri_crop_low_detail": "আর্দ্রতা {hum}% — সাধারণত যে মাত্রা উদ্বেগ বাড়ায় তার চেয়ে কম।",
        "ri_field_title": "আজকের মাঠের পরামর্শ",
        "ri_field_storm": "বজ্রঝড়ের সম্ভাবনা আছে। মাঠের কাজ পিছিয়ে দিয়ে যন্ত্রপাতি নিরাপদে রাখার কথা ভাবুন।",
        "ri_field_rain": "প্রায় {mm} মিমি বৃষ্টি হতে পারে। সেচ দেওয়ার আগে মাঠের আর্দ্রতা দেখার কথা ভাবুন।",
        "ri_field_humid": "আর্দ্রতা {hum}% নিয়ে বেশি। আর্দ্রতাজনিত সমস্যার জন্য ফসলে নজর রাখা কাজে লাগতে পারে।",
        "ri_field_hot": "প্রায় {feels}°C-এর মতো লাগবে। মাটির আর্দ্রতা দেখে সকালে বা সন্ধ্যায় জল দেওয়ার কথা ভাবুন।",
        "ri_field_clear": "বড় কোনো আবহাওয়া পরিবর্তন নেই। মাঠের কাজের জন্য উপযুক্ত সময়।",
        "ri_fishing_title": "মাছ ধরার পরিস্থিতি",
        "ri_fishing_avoid": "এড়ান",
        "ri_fishing_caution": "সতর্কতা",
        "ri_fishing_favorable": "অনুকূল",
        "ri_fishing_detail": "শুধু আবহাওয়ার ভিত্তিতে। বেরোনোর আগে সরকারি সামুদ্রিক সতর্কতা দেখুন।",
        "ri_wind_title": "বাতাস",
        "ri_wind_gust": "দমকা প্রায় {gust} কিমি/ঘণ্টা পর্যন্ত।",
        "ri_storm_title": "বজ্রপাত ও ঝড়ের ঝুঁকি",
        "ri_storm_high": "বেশি",
        "ri_storm_moderate": "মাঝারি",
        "ri_storm_low": "কম",
        "ri_storm_high_detail": "বজ্রঝড়ের সম্ভাবনা বেশি। বেরোনোর আগে সরকারি সতর্কতা দেখুন।",
        "ri_storm_moderate_detail": "বজ্রঝড় হতে পারে। বেরোনোর আগে সরকারি সতর্কতা দেখুন।",
        "ri_storm_low_detail": "এখন ঝড়ের কোনো ইঙ্গিত নেই।",
        "ri_visibility_title": "দৃশ্যমানতা",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "বৃষ্টি",
        "ri_factor_visibility": "কম দৃশ্যমানতা",
        "ri_factor_wind": "জোরে বাতাস",
        "ri_factor_storm": "বজ্রঝড়",
        "ri_trip_title": "ভ্রমণের আবহাওয়া",
        "ri_trip_tomorrow": "আগামীকাল: বৃষ্টির সম্ভাবনা প্রায় {prob}%।",
        "ri_trip_tomorrow_cond": "আগামীকাল: {cond}।",
        "ri_travel_title": "ভ্রমণ ঝুঁকি",
        "ri_travel_high": "বেশি",
        "ri_travel_moderate": "মাঝারি",
        "ri_travel_low": "কম",
        "ri_travel_factors": "কারণ: {factors}।",
        "ri_travel_clear": "এখন কোনো আবহাওয়া কারণ ভ্রমণের বিপক্ষে নেই।",
        "ri_activity_title": "বাইরের কাজকর্ম",
        "ri_activity_poor": "খারাপ",
        "ri_activity_caution": "সতর্ক থাকুন",
        "ri_activity_good": "ভালো",
        "ri_activity_excellent": "চমৎকার",
        "ri_pack_title": "যা সঙ্গে নেবেন",
        "ri_pack_umbrella": "ছাতা",
        "ri_pack_raincoat": "রেইন জ্যাকেট",
        "ri_pack_water": "জল",
        "ri_pack_sun": "রোদ থেকে সুরক্ষা",
        "ri_pack_layer": "গরম পোশাক",
        "ri_pack_windproof": "বাতাস আটকানো পোশাক",
        "ri_pack_nothing": "আবহাওয়ার জন্য বিশেষ কিছু লাগবে না",
        "ri_commute_title": "যাতায়াত ঝুঁকি",
        "ri_commute_high": "বেশি",
        "ri_commute_moderate": "মাঝারি",
        "ri_commute_low": "কম",
        "ri_commute_detail": "শুধু আবহাওয়ার ঝুঁকি — এতে যানজট ধরা হয়নি।",
        "ri_hazards_title": "আবহাওয়া বিপদ",
        "ri_hazards_none": "কিছু পাওয়া যায়নি",
        "ri_departure_title": "সবচেয়ে শান্ত সময়",
        "ri_departure_detail": "পরবর্তী যাতায়াতের সময়ে সবচেয়ে কম আবহাওয়া ঝুঁকি।",
        "ri_reminder_title": "মনে রাখুন",
        "ri_reminder_storm": "ঝড়ের সম্ভাবনা আছে — কিছু বাড়তি সময় রাখুন।",
        "ri_reminder_rain": "ছাতা নিন এবং একটু বাড়তি সময় রাখুন।",
        "ri_reminder_wind": "জোরে বাতাসের সম্ভাবনা — খোলা রাস্তায় সতর্ক থাকুন।",
        "ri_reminder_clear": "আপনার যাতায়াতের জন্য আবহাওয়া অনুকূল দেখাচ্ছে।",
    },
    # -----------------------------------------------------------------------
    "mr": {
        "ri_heading_general": "रोजची हवामान माहिती",
        "ri_heading_farmer": "शेती हवामान माहिती",
        "ri_heading_fisherman": "सागरी हवामान माहिती",
        "ri_heading_traveler": "प्रवास हवामान माहिती",
        "ri_heading_commuter": "प्रवासमार्ग हवामान माहिती",
        "ri_no_data": "माहिती उपलब्ध नाही",
        "ri_note_marine": "या ॲपमध्ये लाटा, स्वेल आणि भरती-ओहोटीची माहिती नाही. हे मूल्यमापन हवामान अंदाजातील वारा, वादळ आणि दृश्यमानतेवर आधारित आहे.",
        "ri_from_risk": "{hazard} पासूनच्या सध्याच्या {level} धोक्यावर आधारित.",
        "ri_umbrella_title": "छत्री",
        "ri_umbrella_yes": "छत्री सोबत ठेवा",
        "ri_umbrella_maybe": "छत्री ठेवणे बरे",
        "ri_umbrella_no": "छत्रीची गरज नाही",
        "ri_umbrella_prob": "पुढील 12 तासांत पावसाची शक्यता सुमारे {prob}% पर्यंत जाते.",
        "ri_umbrella_mm": "24 तासांत सुमारे {mm} मिमी पाऊस अपेक्षित आहे.",
        "ri_comfort_title": "सुखदपणा",
        "ri_comfort_hot": "उकाडा — पाणी पीत राहा",
        "ri_comfort_muggy": "उष्ण आणि दमट",
        "ri_comfort_warm": "उष्ण",
        "ri_comfort_cool": "थंड",
        "ri_comfort_ok": "आरामदायक",
        "ri_comfort_detail": "{hum}% आर्द्रतेत {feels}°C सारखे जाणवते.",
        "ri_comfort_detail_temp": "{feels}°C सारखे जाणवते.",
        "ri_outdoor_title": "बाहेर पडणे",
        "ri_outdoor_avoid": "जास्त वेळ बाहेर राहणे टाळा",
        "ri_outdoor_caution": "काळजी घेऊन बाहेर जा",
        "ri_outdoor_good": "बाहेरील कामासाठी चांगले",
        "ri_rain_title": "पावसाचा परिणाम",
        "ri_rain_high": "जास्त",
        "ri_rain_moderate": "मध्यम",
        "ri_rain_low": "कमी",
        "ri_rain_detail_mm": "पुढील 24 तासांत सुमारे {mm} मिमी अपेक्षित आहे.",
        "ri_rain_detail_prob": "पुढील 12 तासांत पावसाची शक्यता सुमारे {prob}% पर्यंत जाते.",
        "ri_irrigation_title": "पाणी देण्याचा सल्ला",
        "ri_irrigation_nodata": "पाणी देण्याच्या सल्ल्यासाठी पुरेशी पावसाची माहिती नाही",
        "ri_irrigation_delay": "पाणी देणे पुढे ढकलण्याचा विचार करा",
        "ri_irrigation_delay_detail": "पुढील 24 तासांत सुमारे {mm} मिमी पाऊस अपेक्षित आहे.",
        "ri_irrigation_needed": "पाणी देण्याची गरज असू शकते",
        "ri_irrigation_dry_detail": "अंदाजाच्या काळात पाऊस फार कमी किंवा नाही.",
        "ri_irrigation_monitor": "स्थितीवर लक्ष ठेवा",
        "ri_irrigation_monitor_detail": "सुमारे {mm} मिमी अपेक्षित — हलका, पुरेसा नसू शकतो.",
        "ri_crop_title": "पिकावरील हवामान धोका",
        "ri_crop_high": "जास्त",
        "ri_crop_moderate": "मध्यम",
        "ri_crop_low": "कमी",
        "ri_crop_high_detail": "{hum}% आर्द्रतेची उष्ण, ओली हवा ही अशी स्थिती आहे जिथे बुरशीजन्य अडचणींची शक्यता वाढते. पावसानंतर पिके पाहण्याचा विचार करा.",
        "ri_crop_moderate_detail": "आर्द्रता {hum}% आहे. पावसानंतर लक्ष ठेवणे उपयोगी ठरू शकते.",
        "ri_crop_low_detail": "आर्द्रता {hum}% आहे — साधारणपणे चिंता वाढवणाऱ्या पातळीपेक्षा कमी.",
        "ri_field_title": "आजचा शेती सल्ला",
        "ri_field_storm": "वादळी स्थिती शक्य आहे. शेतातील काम पुढे ढकलून अवजारे सुरक्षित ठेवण्याचा विचार करा.",
        "ri_field_rain": "सुमारे {mm} मिमी पाऊस अपेक्षित आहे. पाणी देण्यापूर्वी शेतातील ओलावा पाहण्याचा विचार करा.",
        "ri_field_humid": "आर्द्रता {hum}% इतकी जास्त आहे. ओलाव्याशी संबंधित अडचणींसाठी पिकांवर लक्ष ठेवणे उपयोगी ठरू शकते.",
        "ri_field_hot": "सुमारे {feels}°C सारखे जाणवेल. जमिनीतील ओलावा पाहून सकाळी किंवा संध्याकाळी पाणी देण्याचा विचार करा.",
        "ri_field_clear": "मोठा हवामान बदल दिसत नाही. शेतीच्या कामासाठी योग्य वेळ.",
        "ri_fishing_title": "मासेमारीची स्थिती",
        "ri_fishing_avoid": "टाळा",
        "ri_fishing_caution": "सावधगिरी",
        "ri_fishing_favorable": "अनुकूल",
        "ri_fishing_detail": "फक्त हवामानावर आधारित. बाहेर पडण्यापूर्वी अधिकृत सागरी इशारे पाहा.",
        "ri_wind_title": "वारा",
        "ri_wind_gust": "झोत सुमारे {gust} किमी/तास पर्यंत.",
        "ri_storm_title": "वीज आणि वादळाचा धोका",
        "ri_storm_high": "जास्त",
        "ri_storm_moderate": "मध्यम",
        "ri_storm_low": "कमी",
        "ri_storm_high_detail": "मेघगर्जनेसह वादळाची शक्यता जास्त आहे. बाहेर पडण्यापूर्वी अधिकृत इशारे पाहा.",
        "ri_storm_moderate_detail": "मेघगर्जनेसह वादळ शक्य आहे. बाहेर पडण्यापूर्वी अधिकृत इशारे पाहा.",
        "ri_storm_low_detail": "सध्या वादळाचे कोणतेही संकेत नाहीत.",
        "ri_visibility_title": "दृश्यमानता",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "पाऊस",
        "ri_factor_visibility": "कमी दृश्यमानता",
        "ri_factor_wind": "जोरदार वारा",
        "ri_factor_storm": "वादळ",
        "ri_trip_title": "प्रवासाचे हवामान",
        "ri_trip_tomorrow": "उद्या: पावसाची शक्यता सुमारे {prob}%.",
        "ri_trip_tomorrow_cond": "उद्या: {cond}.",
        "ri_travel_title": "प्रवास धोका",
        "ri_travel_high": "जास्त",
        "ri_travel_moderate": "मध्यम",
        "ri_travel_low": "कमी",
        "ri_travel_factors": "कारणे: {factors}.",
        "ri_travel_clear": "सध्या कोणतेही हवामान कारण प्रवासाच्या विरोधात नाही.",
        "ri_activity_title": "बाहेरील हालचाल",
        "ri_activity_poor": "योग्य नाही",
        "ri_activity_caution": "काळजी घ्या",
        "ri_activity_good": "चांगले",
        "ri_activity_excellent": "उत्तम",
        "ri_pack_title": "सोबत काय घ्यावे",
        "ri_pack_umbrella": "छत्री",
        "ri_pack_raincoat": "रेनकोट",
        "ri_pack_water": "पाणी",
        "ri_pack_sun": "उन्हापासून संरक्षण",
        "ri_pack_layer": "उबदार कपडे",
        "ri_pack_windproof": "वारा अडवणारे कपडे",
        "ri_pack_nothing": "हवामानासाठी विशेष काही नको",
        "ri_commute_title": "प्रवासमार्ग धोका",
        "ri_commute_high": "जास्त",
        "ri_commute_moderate": "मध्यम",
        "ri_commute_low": "कमी",
        "ri_commute_detail": "फक्त हवामानाचा धोका — यात वाहतूक कोंडी नाही.",
        "ri_hazards_title": "हवामान धोके",
        "ri_hazards_none": "काहीही आढळले नाही",
        "ri_departure_title": "सर्वात शांत वेळ",
        "ri_departure_detail": "पुढील प्रवासाच्या वेळेत सर्वात कमी हवामान धोका.",
        "ri_reminder_title": "लक्षात ठेवा",
        "ri_reminder_storm": "वादळी स्थिती शक्य आहे — थोडा जास्त वेळ ठेवा.",
        "ri_reminder_rain": "छत्री सोबत ठेवा आणि थोडा जास्त वेळ ठेवा.",
        "ri_reminder_wind": "जोरदार वारा अपेक्षित — मोकळ्या रस्त्यांवर काळजी घ्या.",
        "ri_reminder_clear": "तुमच्या प्रवासासाठी हवामान अनुकूल दिसते.",
    },
    # -----------------------------------------------------------------------
    "as": {
        "ri_heading_general": "দৈনন্দিন বতৰৰ তথ্য",
        "ri_heading_farmer": "কৃষি বতৰৰ তথ্য",
        "ri_heading_fisherman": "সাগৰীয় বতৰৰ তথ্য",
        "ri_heading_traveler": "ভ্ৰমণ বতৰৰ তথ্য",
        "ri_heading_commuter": "যাতায়াত বতৰৰ তথ্য",
        "ri_no_data": "তথ্য উপলব্ধ নহয়",
        "ri_note_marine": "এই এপত ঢৌ, স্বেল আৰু জোৱাৰ-ভাটাৰ তথ্য নাই। এই মূল্যায়ন বতৰৰ পূৰ্বাভাসৰ বতাহ, ধুমুহা আৰু দৃশ্যমানতাৰ ওপৰত ভিত্তি কৰি কৰা হৈছে।",
        "ri_from_risk": "{hazard}ৰ পৰা বৰ্তমানৰ {level} বিপদৰ ভিত্তিত।",
        "ri_umbrella_title": "ছাতি",
        "ri_umbrella_yes": "ছাতি লওক",
        "ri_umbrella_maybe": "ছাতি ৰখা ভাল",
        "ri_umbrella_no": "ছাতিৰ প্ৰয়োজন নাই",
        "ri_umbrella_prob": "অহা 12 ঘণ্টাত বৰষুণৰ সম্ভাৱনা প্ৰায় {prob}% লৈ যায়।",
        "ri_umbrella_mm": "24 ঘণ্টাত প্ৰায় {mm} মি.মি. বৰষুণ হ'ব পাৰে।",
        "ri_comfort_title": "আৰাম",
        "ri_comfort_hot": "গৰম — পানী খাই থাকক",
        "ri_comfort_muggy": "গৰম আৰু আৰ্দ্ৰ",
        "ri_comfort_warm": "গৰম",
        "ri_comfort_cool": "ঠাণ্ডা",
        "ri_comfort_ok": "আৰামদায়ক",
        "ri_comfort_detail": "{hum}% আৰ্দ্ৰতাত {feels}°C যেন লাগে।",
        "ri_comfort_detail_temp": "{feels}°C যেন লাগে।",
        "ri_outdoor_title": "বাহিৰলৈ ওলোৱা",
        "ri_outdoor_avoid": "বহু সময় বাহিৰত থকা এৰাওক",
        "ri_outdoor_caution": "সাৱধানে বাহিৰলৈ যাওক",
        "ri_outdoor_good": "বাহিৰৰ কামৰ বাবে ভাল",
        "ri_rain_title": "বৰষুণৰ প্ৰভাৱ",
        "ri_rain_high": "বেছি",
        "ri_rain_moderate": "মজলীয়া",
        "ri_rain_low": "কম",
        "ri_rain_detail_mm": "অহা 24 ঘণ্টাত প্ৰায় {mm} মি.মি. হ'ব পাৰে।",
        "ri_rain_detail_prob": "অহা 12 ঘণ্টাত বৰষুণৰ সম্ভাৱনা প্ৰায় {prob}% লৈ যায়।",
        "ri_irrigation_title": "জলসিঞ্চনৰ পৰামৰ্শ",
        "ri_irrigation_nodata": "জলসিঞ্চনৰ পৰামৰ্শৰ বাবে পৰ্যাপ্ত বৰষুণৰ তথ্য নাই",
        "ri_irrigation_delay": "জলসিঞ্চন পিছুৱাই দিয়াৰ কথা ভাবক",
        "ri_irrigation_delay_detail": "অহা 24 ঘণ্টাত প্ৰায় {mm} মি.মি. বৰষুণ হ'ব পাৰে।",
        "ri_irrigation_needed": "জলসিঞ্চনৰ প্ৰয়োজন হ'ব পাৰে",
        "ri_irrigation_dry_detail": "পূৰ্বাভাসৰ সময়ত বৰষুণ অতি কম বা নাই।",
        "ri_irrigation_monitor": "অৱস্থাৰ ওপৰত চকু ৰাখক",
        "ri_irrigation_monitor_detail": "প্ৰায় {mm} মি.মি. হ'ব পাৰে — পাতল, পৰ্যাপ্ত নহ'বও পাৰে।",
        "ri_crop_title": "শস্যৰ ওপৰত বতৰৰ বিপদ",
        "ri_crop_high": "বেছি",
        "ri_crop_moderate": "মজলীয়া",
        "ri_crop_low": "কম",
        "ri_crop_high_detail": "{hum}% আৰ্দ্ৰতাৰ গৰম, তিতা বতাহ এনে অৱস্থা য'ত ছত্ৰাকজনিত সমস্যাৰ সম্ভাৱনা বাঢ়ে। বৰষুণৰ পিছত শস্য চোৱাৰ কথা ভাবক।",
        "ri_crop_moderate_detail": "আৰ্দ্ৰতা {hum}%। বৰষুণৰ পিছত চকু ৰখা উপযোগী হ'ব পাৰে।",
        "ri_crop_low_detail": "আৰ্দ্ৰতা {hum}% — সাধাৰণতে চিন্তা বঢ়োৱা মাত্ৰাতকৈ কম।",
        "ri_field_title": "আজিৰ পথাৰৰ পৰামৰ্শ",
        "ri_field_storm": "ধুমুহাৰ সম্ভাৱনা আছে। পথাৰৰ কাম পিছুৱাই সঁজুলি সুৰক্ষিত ৰখাৰ কথা ভাবক।",
        "ri_field_rain": "প্ৰায় {mm} মি.মি. বৰষুণ হ'ব পাৰে। পানী দিয়াৰ আগতে পথাৰৰ তিতা চোৱাৰ কথা ভাবক।",
        "ri_field_humid": "আৰ্দ্ৰতা {hum}% হৈ বেছি। তিতাজনিত সমস্যাৰ বাবে শস্যত চকু ৰখা উপযোগী হ'ব পাৰে।",
        "ri_field_hot": "প্ৰায় {feels}°C যেন লাগিব। মাটিৰ তিতা চাই ৰাতিপুৱা বা আবেলি পানী দিয়াৰ কথা ভাবক।",
        "ri_field_clear": "ডাঙৰ বতৰৰ সলনি দেখা নাযায়। পথাৰৰ কামৰ বাবে উপযুক্ত সময়।",
        "ri_fishing_title": "মাছ ধৰাৰ অৱস্থা",
        "ri_fishing_avoid": "এৰাওক",
        "ri_fishing_caution": "সাৱধান",
        "ri_fishing_favorable": "অনুকূল",
        "ri_fishing_detail": "কেৱল বতৰৰ ভিত্তিত। ওলোৱাৰ আগতে চৰকাৰী সাগৰীয় সতৰ্কবাণী চাওক।",
        "ri_wind_title": "বতাহ",
        "ri_wind_gust": "দমকা প্ৰায় {gust} কি.মি./ঘণ্টা লৈ।",
        "ri_storm_title": "বিজুলী আৰু ধুমুহাৰ বিপদ",
        "ri_storm_high": "বেছি",
        "ri_storm_moderate": "মজলীয়া",
        "ri_storm_low": "কম",
        "ri_storm_high_detail": "ধুমুহাৰ সম্ভাৱনা বেছি। ওলোৱাৰ আগতে চৰকাৰী সতৰ্কবাণী চাওক।",
        "ri_storm_moderate_detail": "ধুমুহা হ'ব পাৰে। ওলোৱাৰ আগতে চৰকাৰী সতৰ্কবাণী চাওক।",
        "ri_storm_low_detail": "এতিয়া ধুমুহাৰ কোনো সংকেত নাই।",
        "ri_visibility_title": "দৃশ্যমানতা",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "বৰষুণ",
        "ri_factor_visibility": "কম দৃশ্যমানতা",
        "ri_factor_wind": "প্ৰবল বতাহ",
        "ri_factor_storm": "ধুমুহা",
        "ri_trip_title": "ভ্ৰমণৰ বতৰ",
        "ri_trip_tomorrow": "কাইলৈ: বৰষুণৰ সম্ভাৱনা প্ৰায় {prob}%।",
        "ri_trip_tomorrow_cond": "কাইলৈ: {cond}।",
        "ri_travel_title": "ভ্ৰমণৰ বিপদ",
        "ri_travel_high": "বেছি",
        "ri_travel_moderate": "মজলীয়া",
        "ri_travel_low": "কম",
        "ri_travel_factors": "কাৰণ: {factors}।",
        "ri_travel_clear": "এতিয়া কোনো বতৰৰ কাৰণ ভ্ৰমণৰ বিপক্ষে নাই।",
        "ri_activity_title": "বাহিৰৰ কাম",
        "ri_activity_poor": "উপযুক্ত নহয়",
        "ri_activity_caution": "সাৱধান হওক",
        "ri_activity_good": "ভাল",
        "ri_activity_excellent": "অতি ভাল",
        "ri_pack_title": "লগত কি লব",
        "ri_pack_umbrella": "ছাতি",
        "ri_pack_raincoat": "ৰেইন জেকেট",
        "ri_pack_water": "পানী",
        "ri_pack_sun": "ৰ'দৰ পৰা সুৰক্ষা",
        "ri_pack_layer": "গৰম কাপোৰ",
        "ri_pack_windproof": "বতাহ ৰোধী কাপোৰ",
        "ri_pack_nothing": "বতৰৰ বাবে বিশেষ একো নালাগে",
        "ri_commute_title": "যাতায়াতৰ বিপদ",
        "ri_commute_high": "বেছি",
        "ri_commute_moderate": "মজলীয়া",
        "ri_commute_low": "কম",
        "ri_commute_detail": "কেৱল বতৰৰ বিপদ — ইয়াত যান-জঁট ধৰা হোৱা নাই।",
        "ri_hazards_title": "বতৰৰ বিপদ",
        "ri_hazards_none": "একো পোৱা নগ'ল",
        "ri_departure_title": "আটাইতকৈ শান্ত সময়",
        "ri_departure_detail": "অহা যাতায়াতৰ সময়ত আটাইতকৈ কম বতৰৰ বিপদ।",
        "ri_reminder_title": "মনত ৰাখক",
        "ri_reminder_storm": "ধুমুহাৰ সম্ভাৱনা আছে — অলপ অতিৰিক্ত সময় ৰাখক।",
        "ri_reminder_rain": "ছাতি লওক আৰু অলপ অতিৰিক্ত সময় ৰাখক।",
        "ri_reminder_wind": "প্ৰবল বতাহৰ সম্ভাৱনা — মুকলি ৰাস্তাত সাৱধান হওক।",
        "ri_reminder_clear": "আপোনাৰ যাতায়াতৰ বাবে বতৰ অনুকূল দেখা গৈছে।",
    },
}
