# -*- coding: utf-8 -*-
"""Role-intelligence wording, in the six languages the app answers in.

Kept beside the other sentence tables rather than in the frontend, because this
is advisory prose rather than interface chrome: it belongs where every other
sentence WeatherGPT speaks is translated, so the two can never drift.

Same discipline as the rest of the corpus — fixed templates with numeric slots
filled from measured values, so the offline path stays multilingual and stays
incapable of inventing a number. The register is deliberately advisory:
"consider", "monitor", "may", never "must".
"""

from __future__ import annotations

ROLE_SENTENCES: dict[str, dict[str, str]] = {
    # -----------------------------------------------------------------------
    "en": {
        "ri_heading_general": "Everyday weather intelligence",
        "ri_heading_farmer": "Farm intelligence",
        "ri_heading_fisherman": "Marine intelligence",
        "ri_heading_traveler": "Travel intelligence",
        "ri_heading_commuter": "Commute intelligence",
        "ri_no_data": "Data unavailable",
        "ri_note_marine": "Wave, swell and tide data are not available in this app. This reading uses wind, storm and visibility from the weather forecast.",
        "ri_from_risk": "Based on the current {level} risk from {hazard}.",
        # General
        "ri_umbrella_title": "Umbrella",
        "ri_umbrella_yes": "Umbrella recommended",
        "ri_umbrella_maybe": "Worth carrying one",
        "ri_umbrella_no": "Umbrella not necessary",
        "ri_umbrella_prob": "Rain chance peaks near {prob}% in the next 12 hours.",
        "ri_umbrella_mm": "About {mm} mm of rain is expected over 24 hours.",
        "ri_comfort_title": "Comfort",
        "ri_comfort_hot": "Hot — stay hydrated",
        "ri_comfort_muggy": "Warm and humid",
        "ri_comfort_warm": "Warm",
        "ri_comfort_cool": "Cool",
        "ri_comfort_ok": "Comfortable",
        "ri_comfort_detail": "Feels like {feels}°C at {hum}% humidity.",
        "ri_comfort_detail_temp": "Feels like {feels}°C.",
        "ri_outdoor_title": "Outdoors",
        "ri_outdoor_avoid": "Avoid prolonged outdoor activity",
        "ri_outdoor_caution": "Outdoor activity with caution",
        "ri_outdoor_good": "Good for outdoor activity",
        # Farmer
        "ri_rain_title": "Rain impact",
        "ri_rain_high": "High",
        "ri_rain_moderate": "Moderate",
        "ri_rain_low": "Low",
        "ri_rain_detail_mm": "About {mm} mm is expected over the next 24 hours.",
        "ri_rain_detail_prob": "Rain chance peaks near {prob}% in the next 12 hours.",
        "ri_irrigation_title": "Irrigation advisor",
        "ri_irrigation_nodata": "Insufficient rainfall data for an irrigation recommendation",
        "ri_irrigation_delay": "Consider delaying irrigation",
        "ri_irrigation_delay_detail": "About {mm} mm of rain is expected over the next 24 hours.",
        "ri_irrigation_needed": "Irrigation may be needed",
        "ri_irrigation_dry_detail": "Little or no rain is expected in the forecast period.",
        "ri_irrigation_monitor": "Monitor conditions",
        "ri_irrigation_monitor_detail": "About {mm} mm is expected — light, and may not be enough.",
        "ri_crop_title": "Crop weather risk",
        "ri_crop_high": "High",
        "ri_crop_moderate": "Moderate",
        "ri_crop_low": "Low",
        "ri_crop_high_detail": "Warm, wet air at {hum}% humidity is the kind of weather in which fungal problems become more likely. Consider checking crops after rainfall.",
        "ri_crop_moderate_detail": "Humidity is {hum}%. Monitoring after rainfall may be useful.",
        "ri_crop_low_detail": "Humidity is {hum}% — drier than the range that usually raises concern.",
        "ri_field_title": "Today's field advisory",
        "ri_field_storm": "Thunderstorm conditions are possible. Consider postponing field work and securing equipment.",
        "ri_field_rain": "About {mm} mm of rain is expected. Consider checking field moisture before irrigating.",
        "ri_field_humid": "Humidity is high at {hum}%. Monitoring crops for moisture-related problems may be useful.",
        "ri_field_hot": "It will feel around {feels}°C. Consider checking soil moisture and watering early or late in the day.",
        "ri_field_clear": "No significant weather is expected. A usable window for field work.",
        # Fisherman
        "ri_fishing_title": "Fishing conditions",
        "ri_fishing_avoid": "Avoid",
        "ri_fishing_caution": "Caution",
        "ri_fishing_favorable": "Favorable",
        "ri_fishing_detail": "Weather-based only. Check official marine warnings before going out.",
        "ri_wind_title": "Wind",
        "ri_wind_gust": "Gusting to about {gust} km/h.",
        "ri_storm_title": "Lightning and storm risk",
        "ri_storm_high": "High",
        "ri_storm_moderate": "Moderate",
        "ri_storm_low": "Low",
        "ri_storm_high_detail": "Thunderstorm activity is likely. Monitor official warnings before heading out.",
        "ri_storm_moderate_detail": "Thunderstorm activity is possible. Monitor official warnings before heading out.",
        "ri_storm_low_detail": "No thunderstorm activity is indicated right now.",
        "ri_visibility_title": "Visibility",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "rain",
        "ri_factor_visibility": "low visibility",
        "ri_factor_wind": "strong wind",
        "ri_factor_storm": "thunderstorm",
        # Traveller
        "ri_trip_title": "Trip weather",
        "ri_trip_tomorrow": "Tomorrow: about {prob}% chance of rain.",
        "ri_trip_tomorrow_cond": "Tomorrow: {cond}.",
        "ri_travel_title": "Travel risk",
        "ri_travel_high": "High",
        "ri_travel_moderate": "Moderate",
        "ri_travel_low": "Low",
        "ri_travel_factors": "Contributing: {factors}.",
        "ri_travel_clear": "No weather factor is working against travel right now.",
        "ri_activity_title": "Outdoor activity",
        "ri_activity_poor": "Poor",
        "ri_activity_caution": "Use caution",
        "ri_activity_good": "Good",
        "ri_activity_excellent": "Excellent",
        "ri_pack_title": "Packing assistant",
        "ri_pack_umbrella": "Umbrella",
        "ri_pack_raincoat": "Rain jacket",
        "ri_pack_water": "Water",
        "ri_pack_sun": "Sun protection",
        "ri_pack_layer": "Warm layer",
        "ri_pack_windproof": "Windproof layer",
        "ri_pack_nothing": "Nothing weather-specific needed",
        # Commuter
        "ri_commute_title": "Commute risk",
        "ri_commute_high": "High",
        "ri_commute_moderate": "Moderate",
        "ri_commute_low": "Low",
        "ri_commute_detail": "Weather risk only — this does not include traffic.",
        "ri_hazards_title": "Weather hazards",
        "ri_hazards_none": "None detected",
        "ri_departure_title": "Calmest departure",
        "ri_departure_detail": "Lowest weather risk in the next commute window.",
        "ri_reminder_title": "Reminder",
        "ri_reminder_storm": "Storm conditions are possible — consider allowing extra time.",
        "ri_reminder_rain": "Carry an umbrella and allow a little extra time.",
        "ri_reminder_wind": "Strong wind is expected — take care on exposed roads.",
        "ri_reminder_clear": "Weather conditions look favorable for your commute.",
        # --- Map insight: one line per forecast hour ------------------
        "mi_rain_high": "Rain is likely around {time}, near {prob}%.",
        "mi_rain_rising": "Rain chance rises to about {prob}% by {time}.",
        "mi_rain_easing": "Rain chance eases to about {prob}% by {time}.",
        "mi_storm": "Weather risk is {level} around {time}.",
        "mi_wind": "Wind strengthens to about {wind} km/h by {time}.",
        "mi_calm": "No significant weather is indicated around {time}.",
        "mi_role_general": "Carry an umbrella if you are heading out around then.",
        "mi_role_general_calm": "A good window to be outside.",
        "mi_role_farmer": "Consider checking field moisture before irrigating.",
        "mi_role_farmer_calm": "A usable window for field work.",
        "mi_role_fisherman": "Monitor official warnings before considering departure.",
        "mi_role_fisherman_calm": "Still check official marine warnings before going out.",
        "mi_role_traveler": "Consider planning outdoor activities earlier in the day.",
        "mi_role_traveler_calm": "Suitable for outdoor plans.",
        "mi_role_commuter": "Consider leaving earlier if you can.",
        "mi_role_commuter_calm": "A clear window for your commute.",
    },
    # -----------------------------------------------------------------------
    "hi": {
        "ri_heading_general": "रोज़मर्रा की मौसम जानकारी",
        "ri_heading_farmer": "खेती की मौसम जानकारी",
        "ri_heading_fisherman": "समुद्री मौसम जानकारी",
        "ri_heading_traveler": "यात्रा की मौसम जानकारी",
        "ri_heading_commuter": "आवाजाही की मौसम जानकारी",
        "ri_no_data": "जानकारी उपलब्ध नहीं",
        "ri_note_marine": "इस ऐप में लहर, स्वेल और ज्वार-भाटा की जानकारी उपलब्ध नहीं है। यह आकलन मौसम पूर्वानुमान की हवा, तूफ़ान और दृश्यता पर आधारित है।",
        "ri_from_risk": "{hazard} से मौजूदा {level} जोखिम के आधार पर।",
        "ri_umbrella_title": "छाता",
        "ri_umbrella_yes": "छाता साथ रखें",
        "ri_umbrella_maybe": "छाता रखना बेहतर होगा",
        "ri_umbrella_no": "छाते की ज़रूरत नहीं",
        "ri_umbrella_prob": "अगले 12 घंटों में बारिश की संभावना लगभग {prob}% तक पहुँचती है।",
        "ri_umbrella_mm": "24 घंटों में लगभग {mm} मिमी बारिश का अनुमान है।",
        "ri_comfort_title": "आराम",
        "ri_comfort_hot": "गर्मी — पानी पीते रहें",
        "ri_comfort_muggy": "गर्म और उमस भरा",
        "ri_comfort_warm": "गर्म",
        "ri_comfort_cool": "ठंडा",
        "ri_comfort_ok": "आरामदायक",
        "ri_comfort_detail": "{hum}% नमी के साथ {feels}°C जैसा महसूस होता है।",
        "ri_comfort_detail_temp": "{feels}°C जैसा महसूस होता है।",
        "ri_outdoor_title": "बाहर निकलना",
        "ri_outdoor_avoid": "लंबे समय तक बाहर रहने से बचें",
        "ri_outdoor_caution": "सावधानी के साथ बाहर जाएँ",
        "ri_outdoor_good": "बाहर जाने के लिए अच्छा समय",
        "ri_rain_title": "बारिश का असर",
        "ri_rain_high": "अधिक",
        "ri_rain_moderate": "मध्यम",
        "ri_rain_low": "कम",
        "ri_rain_detail_mm": "अगले 24 घंटों में लगभग {mm} मिमी का अनुमान है।",
        "ri_rain_detail_prob": "अगले 12 घंटों में बारिश की संभावना लगभग {prob}% तक पहुँचती है।",
        "ri_irrigation_title": "सिंचाई सलाह",
        "ri_irrigation_nodata": "सिंचाई की सलाह के लिए वर्षा के पर्याप्त आँकड़े नहीं हैं",
        "ri_irrigation_delay": "सिंचाई टालने पर विचार करें",
        "ri_irrigation_delay_detail": "अगले 24 घंटों में लगभग {mm} मिमी बारिश का अनुमान है।",
        "ri_irrigation_needed": "सिंचाई की ज़रूरत हो सकती है",
        "ri_irrigation_dry_detail": "पूर्वानुमान अवधि में बहुत कम या कोई बारिश नहीं दिख रही।",
        "ri_irrigation_monitor": "स्थिति पर नज़र रखें",
        "ri_irrigation_monitor_detail": "लगभग {mm} मिमी का अनुमान है — हल्की, शायद पर्याप्त न हो।",
        "ri_crop_title": "फ़सल पर मौसम का जोखिम",
        "ri_crop_high": "अधिक",
        "ri_crop_moderate": "मध्यम",
        "ri_crop_low": "कम",
        "ri_crop_high_detail": "{hum}% नमी वाला गर्म और गीला मौसम वह स्थिति है जिसमें फफूँद की समस्या की संभावना बढ़ जाती है। बारिश के बाद फ़सल देखने पर विचार करें।",
        "ri_crop_moderate_detail": "नमी {hum}% है। बारिश के बाद निगरानी उपयोगी हो सकती है।",
        "ri_crop_low_detail": "नमी {hum}% है — उस सीमा से कम जो आमतौर पर चिंता बढ़ाती है।",
        "ri_field_title": "आज की खेत सलाह",
        "ri_field_storm": "आँधी-तूफ़ान की स्थिति संभव है। खेत का काम टालने और उपकरण सुरक्षित रखने पर विचार करें।",
        "ri_field_rain": "लगभग {mm} मिमी बारिश का अनुमान है। सिंचाई से पहले खेत की नमी देखने पर विचार करें।",
        "ri_field_humid": "नमी {hum}% के साथ अधिक है। नमी से जुड़ी समस्याओं के लिए फ़सल की निगरानी उपयोगी हो सकती है।",
        "ri_field_hot": "लगभग {feels}°C जैसा महसूस होगा। मिट्टी की नमी देखने और सुबह या शाम पानी देने पर विचार करें।",
        "ri_field_clear": "कोई बड़ा मौसम बदलाव नहीं दिख रहा। खेत के काम के लिए उपयुक्त समय।",
        "ri_fishing_title": "मछली पकड़ने की स्थिति",
        "ri_fishing_avoid": "टालें",
        "ri_fishing_caution": "सावधानी",
        "ri_fishing_favorable": "अनुकूल",
        "ri_fishing_detail": "केवल मौसम के आधार पर। निकलने से पहले आधिकारिक समुद्री चेतावनी देखें।",
        "ri_wind_title": "हवा",
        "ri_wind_gust": "झोंके लगभग {gust} किमी/घंटा तक।",
        "ri_storm_title": "बिजली और तूफ़ान का जोखिम",
        "ri_storm_high": "अधिक",
        "ri_storm_moderate": "मध्यम",
        "ri_storm_low": "कम",
        "ri_storm_high_detail": "गरज के साथ तूफ़ान की संभावना है। निकलने से पहले आधिकारिक चेतावनी देखें।",
        "ri_storm_moderate_detail": "गरज के साथ तूफ़ान संभव है। निकलने से पहले आधिकारिक चेतावनी देखें।",
        "ri_storm_low_detail": "फ़िलहाल तूफ़ान का कोई संकेत नहीं है।",
        "ri_visibility_title": "दृश्यता",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "बारिश",
        "ri_factor_visibility": "कम दृश्यता",
        "ri_factor_wind": "तेज़ हवा",
        "ri_factor_storm": "तूफ़ान",
        "ri_trip_title": "यात्रा का मौसम",
        "ri_trip_tomorrow": "कल: बारिश की संभावना लगभग {prob}%।",
        "ri_trip_tomorrow_cond": "कल: {cond}।",
        "ri_travel_title": "यात्रा जोखिम",
        "ri_travel_high": "अधिक",
        "ri_travel_moderate": "मध्यम",
        "ri_travel_low": "कम",
        "ri_travel_factors": "कारण: {factors}।",
        "ri_travel_clear": "अभी कोई मौसम कारण यात्रा के विरुद्ध नहीं है।",
        "ri_activity_title": "बाहरी गतिविधि",
        "ri_activity_poor": "ख़राब",
        "ri_activity_caution": "सावधानी बरतें",
        "ri_activity_good": "ठीक",
        "ri_activity_excellent": "बहुत अच्छा",
        "ri_pack_title": "सामान की सलाह",
        "ri_pack_umbrella": "छाता",
        "ri_pack_raincoat": "बरसाती",
        "ri_pack_water": "पानी",
        "ri_pack_sun": "धूप से बचाव",
        "ri_pack_layer": "गर्म कपड़े",
        "ri_pack_windproof": "हवा रोकने वाली परत",
        "ri_pack_nothing": "मौसम के लिए कुछ ख़ास ज़रूरी नहीं",
        "ri_commute_title": "आवाजाही जोखिम",
        "ri_commute_high": "अधिक",
        "ri_commute_moderate": "मध्यम",
        "ri_commute_low": "कम",
        "ri_commute_detail": "केवल मौसम का जोखिम — इसमें यातायात शामिल नहीं है।",
        "ri_hazards_title": "मौसम ख़तरे",
        "ri_hazards_none": "कोई नहीं मिला",
        "ri_departure_title": "सबसे शांत समय",
        "ri_departure_detail": "अगली आवाजाही अवधि में सबसे कम मौसम जोखिम।",
        "ri_reminder_title": "याद रखें",
        "ri_reminder_storm": "तूफ़ान की स्थिति संभव है — कुछ अतिरिक्त समय रखें।",
        "ri_reminder_rain": "छाता साथ रखें और थोड़ा अतिरिक्त समय लेकर चलें।",
        "ri_reminder_wind": "तेज़ हवा का अनुमान है — खुली सड़कों पर सावधानी रखें।",
        "ri_reminder_clear": "आपकी आवाजाही के लिए मौसम अनुकूल दिख रहा है।",
        # --- Map insight: one line per forecast hour ------------------
        "mi_rain_high": "{time} के आसपास बारिश की संभावना है, लगभग {prob}%।",
        "mi_rain_rising": "{time} तक बारिश की संभावना बढ़कर लगभग {prob}% हो जाती है।",
        "mi_rain_easing": "{time} तक बारिश की संभावना घटकर लगभग {prob}% रह जाती है।",
        "mi_storm": "{time} के आसपास मौसम जोखिम {level} है।",
        "mi_wind": "{time} तक हवा बढ़कर लगभग {wind} किमी/घंटा हो जाती है।",
        "mi_calm": "{time} के आसपास कोई बड़ा मौसम बदलाव नहीं दिख रहा।",
        "mi_role_general": "उस समय बाहर निकलें तो छाता साथ रखें।",
        "mi_role_general_calm": "बाहर रहने के लिए अच्छा समय।",
        "mi_role_farmer": "सिंचाई से पहले खेत की नमी देखने पर विचार करें।",
        "mi_role_farmer_calm": "खेत के काम के लिए उपयुक्त समय।",
        "mi_role_fisherman": "निकलने से पहले आधिकारिक चेतावनी देखें।",
        "mi_role_fisherman_calm": "फिर भी निकलने से पहले आधिकारिक समुद्री चेतावनी देखें।",
        "mi_role_traveler": "बाहरी गतिविधियाँ दिन में पहले करने पर विचार करें।",
        "mi_role_traveler_calm": "बाहरी योजनाओं के लिए उपयुक्त।",
        "mi_role_commuter": "हो सके तो जल्दी निकलने पर विचार करें।",
        "mi_role_commuter_calm": "आपकी आवाजाही के लिए साफ़ समय।",
    },
    # -----------------------------------------------------------------------
    "te": {
        "ri_heading_general": "రోజువారీ వాతావరణ సమాచారం",
        "ri_heading_farmer": "వ్యవసాయ వాతావరణ సమాచారం",
        "ri_heading_fisherman": "సముద్ర వాతావరణ సమాచారం",
        "ri_heading_traveler": "ప్రయాణ వాతావరణ సమాచారం",
        "ri_heading_commuter": "ప్రయాణ మార్గ వాతావరణ సమాచారం",
        "ri_no_data": "సమాచారం అందుబాటులో లేదు",
        "ri_note_marine": "ఈ యాప్‌లో అలలు, స్వెల్ మరియు ఆటుపోట్ల సమాచారం అందుబాటులో లేదు. ఈ అంచనా వాతావరణ సూచనలోని గాలి, తుఫాను మరియు దృశ్యత ఆధారంగా ఉంది.",
        "ri_from_risk": "{hazard} నుండి ప్రస్తుత {level} ప్రమాదం ఆధారంగా.",
        "ri_umbrella_title": "గొడుగు",
        "ri_umbrella_yes": "గొడుగు తీసుకెళ్లండి",
        "ri_umbrella_maybe": "గొడుగు ఉంచుకోవడం మంచిది",
        "ri_umbrella_no": "గొడుగు అవసరం లేదు",
        "ri_umbrella_prob": "రాబోయే 12 గంటల్లో వర్ష సంభావ్యత సుమారు {prob}% వరకు ఉంటుంది.",
        "ri_umbrella_mm": "24 గంటల్లో సుమారు {mm} మి.మీ. వర్షం అంచనా.",
        "ri_comfort_title": "సౌకర్యం",
        "ri_comfort_hot": "వేడి — నీరు తాగుతూ ఉండండి",
        "ri_comfort_muggy": "వేడి మరియు తేమ",
        "ri_comfort_warm": "వెచ్చగా",
        "ri_comfort_cool": "చల్లగా",
        "ri_comfort_ok": "హాయిగా",
        "ri_comfort_detail": "{hum}% తేమతో {feels}°C లా అనిపిస్తుంది.",
        "ri_comfort_detail_temp": "{feels}°C లా అనిపిస్తుంది.",
        "ri_outdoor_title": "బయటికి వెళ్లడం",
        "ri_outdoor_avoid": "ఎక్కువసేపు బయట ఉండటం మానండి",
        "ri_outdoor_caution": "జాగ్రత్తగా బయటికి వెళ్లండి",
        "ri_outdoor_good": "బయటి పనులకు అనుకూలం",
        "ri_rain_title": "వర్ష ప్రభావం",
        "ri_rain_high": "ఎక్కువ",
        "ri_rain_moderate": "మధ్యస్థం",
        "ri_rain_low": "తక్కువ",
        "ri_rain_detail_mm": "రాబోయే 24 గంటల్లో సుమారు {mm} మి.మీ. అంచనా.",
        "ri_rain_detail_prob": "రాబోయే 12 గంటల్లో వర్ష సంభావ్యత సుమారు {prob}% వరకు ఉంటుంది.",
        "ri_irrigation_title": "నీటిపారుదల సలహా",
        "ri_irrigation_nodata": "నీటిపారుదల సలహాకు తగినంత వర్ష సమాచారం లేదు",
        "ri_irrigation_delay": "నీటిపారుదల వాయిదా వేయడాన్ని పరిశీలించండి",
        "ri_irrigation_delay_detail": "రాబోయే 24 గంటల్లో సుమారు {mm} మి.మీ. వర్షం అంచనా.",
        "ri_irrigation_needed": "నీటిపారుదల అవసరం కావచ్చు",
        "ri_irrigation_dry_detail": "సూచన కాలంలో వర్షం చాలా తక్కువ లేదా లేదు.",
        "ri_irrigation_monitor": "పరిస్థితిని గమనించండి",
        "ri_irrigation_monitor_detail": "సుమారు {mm} మి.మీ. అంచనా — తేలికపాటిది, సరిపోకపోవచ్చు.",
        "ri_crop_title": "పంటలపై వాతావరణ ప్రమాదం",
        "ri_crop_high": "ఎక్కువ",
        "ri_crop_moderate": "మధ్యస్థం",
        "ri_crop_low": "తక్కువ",
        "ri_crop_high_detail": "{hum}% తేమతో కూడిన వెచ్చని, తడి గాలి శిలీంధ్ర సమస్యల అవకాశం పెరిగే వాతావరణం. వర్షం తర్వాత పంటలను చూడటాన్ని పరిశీలించండి.",
        "ri_crop_moderate_detail": "తేమ {hum}%. వర్షం తర్వాత గమనించడం ఉపయోగకరం కావచ్చు.",
        "ri_crop_low_detail": "తేమ {hum}% — సాధారణంగా ఆందోళన కలిగించే స్థాయి కంటే తక్కువ.",
        "ri_field_title": "నేటి పొలం సలహా",
        "ri_field_storm": "ఉరుములతో కూడిన తుఫాను అవకాశం ఉంది. పొలం పనులు వాయిదా వేసి, పరికరాలను భద్రపరచడాన్ని పరిశీలించండి.",
        "ri_field_rain": "సుమారు {mm} మి.మీ. వర్షం అంచనా. నీరు పెట్టే ముందు పొలంలో తేమను చూడటాన్ని పరిశీలించండి.",
        "ri_field_humid": "తేమ {hum}% తో ఎక్కువగా ఉంది. తేమ సంబంధిత సమస్యల కోసం పంటలను గమనించడం ఉపయోగకరం కావచ్చు.",
        "ri_field_hot": "సుమారు {feels}°C లా అనిపిస్తుంది. నేల తేమను చూసి, ఉదయం లేదా సాయంత్రం నీరు పెట్టడాన్ని పరిశీలించండి.",
        "ri_field_clear": "పెద్ద వాతావరణ మార్పు కనిపించడం లేదు. పొలం పనులకు అనుకూల సమయం.",
        "ri_fishing_title": "చేపల వేట పరిస్థితి",
        "ri_fishing_avoid": "వద్దు",
        "ri_fishing_caution": "జాగ్రత్త",
        "ri_fishing_favorable": "అనుకూలం",
        "ri_fishing_detail": "వాతావరణం ఆధారంగా మాత్రమే. బయలుదేరే ముందు అధికారిక సముద్ర హెచ్చరికలను చూడండి.",
        "ri_wind_title": "గాలి",
        "ri_wind_gust": "గాలి తాకిడి సుమారు {gust} కి.మీ./గం. వరకు.",
        "ri_storm_title": "పిడుగులు మరియు తుఫాను ప్రమాదం",
        "ri_storm_high": "ఎక్కువ",
        "ri_storm_moderate": "మధ్యస్థం",
        "ri_storm_low": "తక్కువ",
        "ri_storm_high_detail": "ఉరుములతో కూడిన తుఫాను అవకాశం ఎక్కువ. బయలుదేరే ముందు అధికారిక హెచ్చరికలను చూడండి.",
        "ri_storm_moderate_detail": "ఉరుములతో కూడిన తుఫాను సాధ్యం. బయలుదేరే ముందు అధికారిక హెచ్చరికలను చూడండి.",
        "ri_storm_low_detail": "ప్రస్తుతం తుఫాను సూచనలు లేవు.",
        "ri_visibility_title": "దృశ్యత",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "వర్షం",
        "ri_factor_visibility": "తక్కువ దృశ్యత",
        "ri_factor_wind": "బలమైన గాలి",
        "ri_factor_storm": "తుఫాను",
        "ri_trip_title": "ప్రయాణ వాతావరణం",
        "ri_trip_tomorrow": "రేపు: వర్ష సంభావ్యత సుమారు {prob}%.",
        "ri_trip_tomorrow_cond": "రేపు: {cond}.",
        "ri_travel_title": "ప్రయాణ ప్రమాదం",
        "ri_travel_high": "ఎక్కువ",
        "ri_travel_moderate": "మధ్యస్థం",
        "ri_travel_low": "తక్కువ",
        "ri_travel_factors": "కారణాలు: {factors}.",
        "ri_travel_clear": "ప్రస్తుతం ప్రయాణానికి వ్యతిరేకంగా ఏ వాతావరణ కారణం లేదు.",
        "ri_activity_title": "బయటి కార్యకలాపాలు",
        "ri_activity_poor": "అనుకూలం కాదు",
        "ri_activity_caution": "జాగ్రత్త అవసరం",
        "ri_activity_good": "బాగుంది",
        "ri_activity_excellent": "చాలా బాగుంది",
        "ri_pack_title": "సర్దుకోవాల్సినవి",
        "ri_pack_umbrella": "గొడుగు",
        "ri_pack_raincoat": "రेయిన్ జాకెట్",
        "ri_pack_water": "నీరు",
        "ri_pack_sun": "ఎండ నుండి రక్షణ",
        "ri_pack_layer": "వెచ్చని దుస్తులు",
        "ri_pack_windproof": "గాలిని ఆపే దుస్తులు",
        "ri_pack_nothing": "వాతావరణం కోసం ప్రత్యేకంగా ఏమీ అవసరం లేదు",
        "ri_commute_title": "ప్రయాణ మార్గ ప్రమాదం",
        "ri_commute_high": "ఎక్కువ",
        "ri_commute_moderate": "మధ్యస్థం",
        "ri_commute_low": "తక్కువ",
        "ri_commute_detail": "వాతావరణ ప్రమాదం మాత్రమే — ఇందులో ట్రాఫిక్ లేదు.",
        "ri_hazards_title": "వాతావరణ ప్రమాదాలు",
        "ri_hazards_none": "ఏవీ కనిపించలేదు",
        "ri_departure_title": "ప్రశాంతమైన సమయం",
        "ri_departure_detail": "రాబోయే ప్రయాణ సమయంలో అత్యల్ప వాతావరణ ప్రమాదం.",
        "ri_reminder_title": "గుర్తుంచుకోండి",
        "ri_reminder_storm": "తుఫాను పరిస్థితి సాధ్యం — కొంత అదనపు సమయం తీసుకోండి.",
        "ri_reminder_rain": "గొడుగు తీసుకెళ్లండి, కొంత అదనపు సమయం ఉంచుకోండి.",
        "ri_reminder_wind": "బలమైన గాలి అంచనా — బహిరంగ రహదారులపై జాగ్రత్త.",
        "ri_reminder_clear": "మీ ప్రయాణానికి వాతావరణం అనుకూలంగా ఉంది.",
        # --- Map insight: one line per forecast hour ------------------
        "mi_rain_high": "{time} ప్రాంతంలో వర్షం పడే అవకాశం ఉంది, సుమారు {prob}%.",
        "mi_rain_rising": "{time} నాటికి వర్ష సంభావ్యత సుమారు {prob}% కి పెరుగుతుంది.",
        "mi_rain_easing": "{time} నాటికి వర్ష సంభావ్యత సుమారు {prob}% కి తగ్గుతుంది.",
        "mi_storm": "{time} ప్రాంతంలో వాతావరణ ప్రమాదం {level}.",
        "mi_wind": "{time} నాటికి గాలి సుమారు {wind} కి.మీ./గం. కి పెరుగుతుంది.",
        "mi_calm": "{time} ప్రాంతంలో పెద్ద వాతావరణ మార్పు కనిపించడం లేదు.",
        "mi_role_general": "ఆ సమయంలో బయటికి వెళ్తే గొడుగు తీసుకెళ్లండి.",
        "mi_role_general_calm": "బయట ఉండటానికి మంచి సమయం.",
        "mi_role_farmer": "నీరు పెట్టే ముందు పొలంలో తేమను చూడటాన్ని పరిశీలించండి.",
        "mi_role_farmer_calm": "పొలం పనులకు అనుకూల సమయం.",
        "mi_role_fisherman": "బయలుదేరే ముందు అధికారిక హెచ్చరికలను చూడండి.",
        "mi_role_fisherman_calm": "అయినా బయలుదేరే ముందు అధికారిక సముద్ర హెచ్చరికలను చూడండి.",
        "mi_role_traveler": "బయటి కార్యకలాపాలను రోజులో ముందుగా ప్లాన్ చేయడాన్ని పరిశీలించండి.",
        "mi_role_traveler_calm": "బయటి ప్రణాళికలకు అనుకూలం.",
        "mi_role_commuter": "వీలైతే ముందుగా బయలుదేరడాన్ని పరిశీలించండి.",
        "mi_role_commuter_calm": "మీ ప్రయాణానికి స్పష్టమైన సమయం.",
    },
    # -----------------------------------------------------------------------
    "bn": {
        "ri_heading_general": "দৈনন্দিন আবহাওয়া তথ্য",
        "ri_heading_farmer": "কৃষি আবহাওয়া তথ্য",
        "ri_heading_fisherman": "সামুদ্রিক আবহাওয়া তথ্য",
        "ri_heading_traveler": "ভ্রমণ আবহাওয়া তথ্য",
        "ri_heading_commuter": "যাতায়াত আবহাওয়া তথ্য",
        "ri_no_data": "তথ্য পাওয়া যায়নি",
        "ri_note_marine": "এই অ্যাপে ঢেউ, স্বেল ও জোয়ার-ভাটার তথ্য নেই। এই মূল্যায়ন আবহাওয়া পূর্বাভাসের বাতাস, ঝড় ও দৃশ্যমানতার উপর ভিত্তি করে।",
        "ri_from_risk": "{hazard} থেকে বর্তমান {level} ঝুঁকির ভিত্তিতে।",
        "ri_umbrella_title": "ছাতা",
        "ri_umbrella_yes": "ছাতা নিন",
        "ri_umbrella_maybe": "ছাতা রাখা ভালো",
        "ri_umbrella_no": "ছাতার দরকার নেই",
        "ri_umbrella_prob": "আগামী 12 ঘণ্টায় বৃষ্টির সম্ভাবনা প্রায় {prob}% পর্যন্ত ওঠে।",
        "ri_umbrella_mm": "24 ঘণ্টায় প্রায় {mm} মিমি বৃষ্টি হতে পারে।",
        "ri_comfort_title": "স্বাচ্ছন্দ্য",
        "ri_comfort_hot": "গরম — পানি পান করতে থাকুন",
        "ri_comfort_muggy": "গরম ও আর্দ্র",
        "ri_comfort_warm": "গরম",
        "ri_comfort_cool": "ঠান্ডা",
        "ri_comfort_ok": "আরামদায়ক",
        "ri_comfort_detail": "{hum}% আর্দ্রতায় {feels}°C-এর মতো লাগে।",
        "ri_comfort_detail_temp": "{feels}°C-এর মতো লাগে।",
        "ri_outdoor_title": "বাইরে বেরোনো",
        "ri_outdoor_avoid": "দীর্ঘক্ষণ বাইরে থাকা এড়ান",
        "ri_outdoor_caution": "সতর্ক থেকে বাইরে যান",
        "ri_outdoor_good": "বাইরের কাজের জন্য ভালো",
        "ri_rain_title": "বৃষ্টির প্রভাব",
        "ri_rain_high": "বেশি",
        "ri_rain_moderate": "মাঝারি",
        "ri_rain_low": "কম",
        "ri_rain_detail_mm": "আগামী 24 ঘণ্টায় প্রায় {mm} মিমি হতে পারে।",
        "ri_rain_detail_prob": "আগামী 12 ঘণ্টায় বৃষ্টির সম্ভাবনা প্রায় {prob}% পর্যন্ত ওঠে।",
        "ri_irrigation_title": "সেচ পরামর্শ",
        "ri_irrigation_nodata": "সেচের পরামর্শের জন্য যথেষ্ট বৃষ্টির তথ্য নেই",
        "ri_irrigation_delay": "সেচ পিছিয়ে দেওয়ার কথা ভাবুন",
        "ri_irrigation_delay_detail": "আগামী 24 ঘণ্টায় প্রায় {mm} মিমি বৃষ্টি হতে পারে।",
        "ri_irrigation_needed": "সেচের দরকার হতে পারে",
        "ri_irrigation_dry_detail": "পূর্বাভাসের সময়ে বৃষ্টি খুব কম বা নেই।",
        "ri_irrigation_monitor": "পরিস্থিতির উপর নজর রাখুন",
        "ri_irrigation_monitor_detail": "প্রায় {mm} মিমি হতে পারে — হালকা, যথেষ্ট নাও হতে পারে।",
        "ri_crop_title": "ফসলে আবহাওয়ার ঝুঁকি",
        "ri_crop_high": "বেশি",
        "ri_crop_moderate": "মাঝারি",
        "ri_crop_low": "কম",
        "ri_crop_high_detail": "{hum}% আর্দ্রতাযুক্ত গরম, ভেজা বাতাস এমন আবহাওয়া যেখানে ছত্রাকজনিত সমস্যার সম্ভাবনা বাড়ে। বৃষ্টির পরে ফসল দেখার কথা ভাবুন।",
        "ri_crop_moderate_detail": "আর্দ্রতা {hum}%। বৃষ্টির পরে নজর রাখা কাজে লাগতে পারে।",
        "ri_crop_low_detail": "আর্দ্রতা {hum}% — সাধারণত যে মাত্রা উদ্বেগ বাড়ায় তার চেয়ে কম।",
        "ri_field_title": "আজকের মাঠের পরামর্শ",
        "ri_field_storm": "বজ্রঝড়ের সম্ভাবনা আছে। মাঠের কাজ পিছিয়ে দিয়ে যন্ত্রপাতি নিরাপদে রাখার কথা ভাবুন।",
        "ri_field_rain": "প্রায় {mm} মিমি বৃষ্টি হতে পারে। সেচ দেওয়ার আগে মাঠের আর্দ্রতা দেখার কথা ভাবুন।",
        "ri_field_humid": "আর্দ্রতা {hum}% নিয়ে বেশি। আর্দ্রতাজনিত সমস্যার জন্য ফসলে নজর রাখা কাজে লাগতে পারে।",
        "ri_field_hot": "প্রায় {feels}°C-এর মতো লাগবে। মাটির আর্দ্রতা দেখে সকালে বা সন্ধ্যায় জল দেওয়ার কথা ভাবুন।",
        "ri_field_clear": "বড় কোনো আবহাওয়া পরিবর্তন নেই। মাঠের কাজের জন্য উপযুক্ত সময়।",
        "ri_fishing_title": "মাছ ধরার পরিস্থিতি",
        "ri_fishing_avoid": "এড়ান",
        "ri_fishing_caution": "সতর্কতা",
        "ri_fishing_favorable": "অনুকূল",
        "ri_fishing_detail": "শুধু আবহাওয়ার ভিত্তিতে। বেরোনোর আগে সরকারি সামুদ্রিক সতর্কতা দেখুন।",
        "ri_wind_title": "বাতাস",
        "ri_wind_gust": "দমকা প্রায় {gust} কিমি/ঘণ্টা পর্যন্ত।",
        "ri_storm_title": "বজ্রপাত ও ঝড়ের ঝুঁকি",
        "ri_storm_high": "বেশি",
        "ri_storm_moderate": "মাঝারি",
        "ri_storm_low": "কম",
        "ri_storm_high_detail": "বজ্রঝড়ের সম্ভাবনা বেশি। বেরোনোর আগে সরকারি সতর্কতা দেখুন।",
        "ri_storm_moderate_detail": "বজ্রঝড় হতে পারে। বেরোনোর আগে সরকারি সতর্কতা দেখুন।",
        "ri_storm_low_detail": "এখন ঝড়ের কোনো ইঙ্গিত নেই।",
        "ri_visibility_title": "দৃশ্যমানতা",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "বৃষ্টি",
        "ri_factor_visibility": "কম দৃশ্যমানতা",
        "ri_factor_wind": "জোরে বাতাস",
        "ri_factor_storm": "বজ্রঝড়",
        "ri_trip_title": "ভ্রমণের আবহাওয়া",
        "ri_trip_tomorrow": "আগামীকাল: বৃষ্টির সম্ভাবনা প্রায় {prob}%।",
        "ri_trip_tomorrow_cond": "আগামীকাল: {cond}।",
        "ri_travel_title": "ভ্রমণ ঝুঁকি",
        "ri_travel_high": "বেশি",
        "ri_travel_moderate": "মাঝারি",
        "ri_travel_low": "কম",
        "ri_travel_factors": "কারণ: {factors}।",
        "ri_travel_clear": "এখন কোনো আবহাওয়া কারণ ভ্রমণের বিপক্ষে নেই।",
        "ri_activity_title": "বাইরের কাজকর্ম",
        "ri_activity_poor": "খারাপ",
        "ri_activity_caution": "সতর্ক থাকুন",
        "ri_activity_good": "ভালো",
        "ri_activity_excellent": "চমৎকার",
        "ri_pack_title": "যা সঙ্গে নেবেন",
        "ri_pack_umbrella": "ছাতা",
        "ri_pack_raincoat": "রেইন জ্যাকেট",
        "ri_pack_water": "জল",
        "ri_pack_sun": "রোদ থেকে সুরক্ষা",
        "ri_pack_layer": "গরম পোশাক",
        "ri_pack_windproof": "বাতাস আটকানো পোশাক",
        "ri_pack_nothing": "আবহাওয়ার জন্য বিশেষ কিছু লাগবে না",
        "ri_commute_title": "যাতায়াত ঝুঁকি",
        "ri_commute_high": "বেশি",
        "ri_commute_moderate": "মাঝারি",
        "ri_commute_low": "কম",
        "ri_commute_detail": "শুধু আবহাওয়ার ঝুঁকি — এতে যানজট ধরা হয়নি।",
        "ri_hazards_title": "আবহাওয়া বিপদ",
        "ri_hazards_none": "কিছু পাওয়া যায়নি",
        "ri_departure_title": "সবচেয়ে শান্ত সময়",
        "ri_departure_detail": "পরবর্তী যাতায়াতের সময়ে সবচেয়ে কম আবহাওয়া ঝুঁকি।",
        "ri_reminder_title": "মনে রাখুন",
        "ri_reminder_storm": "ঝড়ের সম্ভাবনা আছে — কিছু বাড়তি সময় রাখুন।",
        "ri_reminder_rain": "ছাতা নিন এবং একটু বাড়তি সময় রাখুন।",
        "ri_reminder_wind": "জোরে বাতাসের সম্ভাবনা — খোলা রাস্তায় সতর্ক থাকুন।",
        "ri_reminder_clear": "আপনার যাতায়াতের জন্য আবহাওয়া অনুকূল দেখাচ্ছে।",
        # --- Map insight: one line per forecast hour ------------------
        "mi_rain_high": "{time} নাগাদ বৃষ্টির সম্ভাবনা আছে, প্রায় {prob}%।",
        "mi_rain_rising": "{time} নাগাদ বৃষ্টির সম্ভাবনা বেড়ে প্রায় {prob}% হয়।",
        "mi_rain_easing": "{time} নাগাদ বৃষ্টির সম্ভাবনা কমে প্রায় {prob}% হয়।",
        "mi_storm": "{time} নাগাদ আবহাওয়ার ঝুঁকি {level}।",
        "mi_wind": "{time} নাগাদ বাতাস বেড়ে প্রায় {wind} কিমি/ঘণ্টা হয়।",
        "mi_calm": "{time} নাগাদ বড় কোনো আবহাওয়া পরিবর্তন নেই।",
        "mi_role_general": "ওই সময়ে বেরোলে ছাতা সঙ্গে নিন।",
        "mi_role_general_calm": "বাইরে থাকার জন্য ভালো সময়।",
        "mi_role_farmer": "সেচ দেওয়ার আগে মাঠের আর্দ্রতা দেখার কথা ভাবুন।",
        "mi_role_farmer_calm": "মাঠের কাজের জন্য উপযুক্ত সময়।",
        "mi_role_fisherman": "বেরোনোর আগে সরকারি সতর্কতা দেখুন।",
        "mi_role_fisherman_calm": "তবুও বেরোনোর আগে সরকারি সামুদ্রিক সতর্কতা দেখুন।",
        "mi_role_traveler": "বাইরের কাজ দিনের আগের দিকে পরিকল্পনা করার কথা ভাবুন।",
        "mi_role_traveler_calm": "বাইরের পরিকল্পনার জন্য উপযুক্ত।",
        "mi_role_commuter": "সম্ভব হলে আগে বেরোনোর কথা ভাবুন।",
        "mi_role_commuter_calm": "আপনার যাতায়াতের জন্য পরিষ্কার সময়।",
    },
    # -----------------------------------------------------------------------
    "mr": {
        "ri_heading_general": "रोजची हवामान माहिती",
        "ri_heading_farmer": "शेती हवामान माहिती",
        "ri_heading_fisherman": "सागरी हवामान माहिती",
        "ri_heading_traveler": "प्रवास हवामान माहिती",
        "ri_heading_commuter": "प्रवासमार्ग हवामान माहिती",
        "ri_no_data": "माहिती उपलब्ध नाही",
        "ri_note_marine": "या ॲपमध्ये लाटा, स्वेल आणि भरती-ओहोटीची माहिती नाही. हे मूल्यमापन हवामान अंदाजातील वारा, वादळ आणि दृश्यमानतेवर आधारित आहे.",
        "ri_from_risk": "{hazard} पासूनच्या सध्याच्या {level} धोक्यावर आधारित.",
        "ri_umbrella_title": "छत्री",
        "ri_umbrella_yes": "छत्री सोबत ठेवा",
        "ri_umbrella_maybe": "छत्री ठेवणे बरे",
        "ri_umbrella_no": "छत्रीची गरज नाही",
        "ri_umbrella_prob": "पुढील 12 तासांत पावसाची शक्यता सुमारे {prob}% पर्यंत जाते.",
        "ri_umbrella_mm": "24 तासांत सुमारे {mm} मिमी पाऊस अपेक्षित आहे.",
        "ri_comfort_title": "सुखदपणा",
        "ri_comfort_hot": "उकाडा — पाणी पीत राहा",
        "ri_comfort_muggy": "उष्ण आणि दमट",
        "ri_comfort_warm": "उष्ण",
        "ri_comfort_cool": "थंड",
        "ri_comfort_ok": "आरामदायक",
        "ri_comfort_detail": "{hum}% आर्द्रतेत {feels}°C सारखे जाणवते.",
        "ri_comfort_detail_temp": "{feels}°C सारखे जाणवते.",
        "ri_outdoor_title": "बाहेर पडणे",
        "ri_outdoor_avoid": "जास्त वेळ बाहेर राहणे टाळा",
        "ri_outdoor_caution": "काळजी घेऊन बाहेर जा",
        "ri_outdoor_good": "बाहेरील कामासाठी चांगले",
        "ri_rain_title": "पावसाचा परिणाम",
        "ri_rain_high": "जास्त",
        "ri_rain_moderate": "मध्यम",
        "ri_rain_low": "कमी",
        "ri_rain_detail_mm": "पुढील 24 तासांत सुमारे {mm} मिमी अपेक्षित आहे.",
        "ri_rain_detail_prob": "पुढील 12 तासांत पावसाची शक्यता सुमारे {prob}% पर्यंत जाते.",
        "ri_irrigation_title": "पाणी देण्याचा सल्ला",
        "ri_irrigation_nodata": "पाणी देण्याच्या सल्ल्यासाठी पुरेशी पावसाची माहिती नाही",
        "ri_irrigation_delay": "पाणी देणे पुढे ढकलण्याचा विचार करा",
        "ri_irrigation_delay_detail": "पुढील 24 तासांत सुमारे {mm} मिमी पाऊस अपेक्षित आहे.",
        "ri_irrigation_needed": "पाणी देण्याची गरज असू शकते",
        "ri_irrigation_dry_detail": "अंदाजाच्या काळात पाऊस फार कमी किंवा नाही.",
        "ri_irrigation_monitor": "स्थितीवर लक्ष ठेवा",
        "ri_irrigation_monitor_detail": "सुमारे {mm} मिमी अपेक्षित — हलका, पुरेसा नसू शकतो.",
        "ri_crop_title": "पिकावरील हवामान धोका",
        "ri_crop_high": "जास्त",
        "ri_crop_moderate": "मध्यम",
        "ri_crop_low": "कमी",
        "ri_crop_high_detail": "{hum}% आर्द्रतेची उष्ण, ओली हवा ही अशी स्थिती आहे जिथे बुरशीजन्य अडचणींची शक्यता वाढते. पावसानंतर पिके पाहण्याचा विचार करा.",
        "ri_crop_moderate_detail": "आर्द्रता {hum}% आहे. पावसानंतर लक्ष ठेवणे उपयोगी ठरू शकते.",
        "ri_crop_low_detail": "आर्द्रता {hum}% आहे — साधारणपणे चिंता वाढवणाऱ्या पातळीपेक्षा कमी.",
        "ri_field_title": "आजचा शेती सल्ला",
        "ri_field_storm": "वादळी स्थिती शक्य आहे. शेतातील काम पुढे ढकलून अवजारे सुरक्षित ठेवण्याचा विचार करा.",
        "ri_field_rain": "सुमारे {mm} मिमी पाऊस अपेक्षित आहे. पाणी देण्यापूर्वी शेतातील ओलावा पाहण्याचा विचार करा.",
        "ri_field_humid": "आर्द्रता {hum}% इतकी जास्त आहे. ओलाव्याशी संबंधित अडचणींसाठी पिकांवर लक्ष ठेवणे उपयोगी ठरू शकते.",
        "ri_field_hot": "सुमारे {feels}°C सारखे जाणवेल. जमिनीतील ओलावा पाहून सकाळी किंवा संध्याकाळी पाणी देण्याचा विचार करा.",
        "ri_field_clear": "मोठा हवामान बदल दिसत नाही. शेतीच्या कामासाठी योग्य वेळ.",
        "ri_fishing_title": "मासेमारीची स्थिती",
        "ri_fishing_avoid": "टाळा",
        "ri_fishing_caution": "सावधगिरी",
        "ri_fishing_favorable": "अनुकूल",
        "ri_fishing_detail": "फक्त हवामानावर आधारित. बाहेर पडण्यापूर्वी अधिकृत सागरी इशारे पाहा.",
        "ri_wind_title": "वारा",
        "ri_wind_gust": "झोत सुमारे {gust} किमी/तास पर्यंत.",
        "ri_storm_title": "वीज आणि वादळाचा धोका",
        "ri_storm_high": "जास्त",
        "ri_storm_moderate": "मध्यम",
        "ri_storm_low": "कमी",
        "ri_storm_high_detail": "मेघगर्जनेसह वादळाची शक्यता जास्त आहे. बाहेर पडण्यापूर्वी अधिकृत इशारे पाहा.",
        "ri_storm_moderate_detail": "मेघगर्जनेसह वादळ शक्य आहे. बाहेर पडण्यापूर्वी अधिकृत इशारे पाहा.",
        "ri_storm_low_detail": "सध्या वादळाचे कोणतेही संकेत नाहीत.",
        "ri_visibility_title": "दृश्यमानता",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "पाऊस",
        "ri_factor_visibility": "कमी दृश्यमानता",
        "ri_factor_wind": "जोरदार वारा",
        "ri_factor_storm": "वादळ",
        "ri_trip_title": "प्रवासाचे हवामान",
        "ri_trip_tomorrow": "उद्या: पावसाची शक्यता सुमारे {prob}%.",
        "ri_trip_tomorrow_cond": "उद्या: {cond}.",
        "ri_travel_title": "प्रवास धोका",
        "ri_travel_high": "जास्त",
        "ri_travel_moderate": "मध्यम",
        "ri_travel_low": "कमी",
        "ri_travel_factors": "कारणे: {factors}.",
        "ri_travel_clear": "सध्या कोणतेही हवामान कारण प्रवासाच्या विरोधात नाही.",
        "ri_activity_title": "बाहेरील हालचाल",
        "ri_activity_poor": "योग्य नाही",
        "ri_activity_caution": "काळजी घ्या",
        "ri_activity_good": "चांगले",
        "ri_activity_excellent": "उत्तम",
        "ri_pack_title": "सोबत काय घ्यावे",
        "ri_pack_umbrella": "छत्री",
        "ri_pack_raincoat": "रेनकोट",
        "ri_pack_water": "पाणी",
        "ri_pack_sun": "उन्हापासून संरक्षण",
        "ri_pack_layer": "उबदार कपडे",
        "ri_pack_windproof": "वारा अडवणारे कपडे",
        "ri_pack_nothing": "हवामानासाठी विशेष काही नको",
        "ri_commute_title": "प्रवासमार्ग धोका",
        "ri_commute_high": "जास्त",
        "ri_commute_moderate": "मध्यम",
        "ri_commute_low": "कमी",
        "ri_commute_detail": "फक्त हवामानाचा धोका — यात वाहतूक कोंडी नाही.",
        "ri_hazards_title": "हवामान धोके",
        "ri_hazards_none": "काहीही आढळले नाही",
        "ri_departure_title": "सर्वात शांत वेळ",
        "ri_departure_detail": "पुढील प्रवासाच्या वेळेत सर्वात कमी हवामान धोका.",
        "ri_reminder_title": "लक्षात ठेवा",
        "ri_reminder_storm": "वादळी स्थिती शक्य आहे — थोडा जास्त वेळ ठेवा.",
        "ri_reminder_rain": "छत्री सोबत ठेवा आणि थोडा जास्त वेळ ठेवा.",
        "ri_reminder_wind": "जोरदार वारा अपेक्षित — मोकळ्या रस्त्यांवर काळजी घ्या.",
        "ri_reminder_clear": "तुमच्या प्रवासासाठी हवामान अनुकूल दिसते.",
        # --- Map insight: one line per forecast hour ------------------
        "mi_rain_high": "{time} च्या सुमारास पावसाची शक्यता आहे, सुमारे {prob}%.",
        "mi_rain_rising": "{time} पर्यंत पावसाची शक्यता वाढून सुमारे {prob}% होते.",
        "mi_rain_easing": "{time} पर्यंत पावसाची शक्यता कमी होऊन सुमारे {prob}% राहते.",
        "mi_storm": "{time} च्या सुमारास हवामान धोका {level} आहे.",
        "mi_wind": "{time} पर्यंत वारा वाढून सुमारे {wind} किमी/तास होतो.",
        "mi_calm": "{time} च्या सुमारास मोठा हवामान बदल दिसत नाही.",
        "mi_role_general": "त्या वेळी बाहेर पडत असाल तर छत्री सोबत ठेवा.",
        "mi_role_general_calm": "बाहेर राहण्यासाठी चांगला वेळ.",
        "mi_role_farmer": "पाणी देण्यापूर्वी शेतातील ओलावा पाहण्याचा विचार करा.",
        "mi_role_farmer_calm": "शेतीच्या कामासाठी योग्य वेळ.",
        "mi_role_fisherman": "बाहेर पडण्यापूर्वी अधिकृत इशारे पाहा.",
        "mi_role_fisherman_calm": "तरीही बाहेर पडण्यापूर्वी अधिकृत सागरी इशारे पाहा.",
        "mi_role_traveler": "बाहेरील कामे दिवसा लवकर करण्याचा विचार करा.",
        "mi_role_traveler_calm": "बाहेरील योजनांसाठी योग्य.",
        "mi_role_commuter": "शक्य असल्यास लवकर निघण्याचा विचार करा.",
        "mi_role_commuter_calm": "तुमच्या प्रवासासाठी मोकळा वेळ.",
    },
    # -----------------------------------------------------------------------
    "as": {
        "ri_heading_general": "দৈনন্দিন বতৰৰ তথ্য",
        "ri_heading_farmer": "কৃষি বতৰৰ তথ্য",
        "ri_heading_fisherman": "সাগৰীয় বতৰৰ তথ্য",
        "ri_heading_traveler": "ভ্ৰমণ বতৰৰ তথ্য",
        "ri_heading_commuter": "যাতায়াত বতৰৰ তথ্য",
        "ri_no_data": "তথ্য উপলব্ধ নহয়",
        "ri_note_marine": "এই এপত ঢৌ, স্বেল আৰু জোৱাৰ-ভাটাৰ তথ্য নাই। এই মূল্যায়ন বতৰৰ পূৰ্বাভাসৰ বতাহ, ধুমুহা আৰু দৃশ্যমানতাৰ ওপৰত ভিত্তি কৰি কৰা হৈছে।",
        "ri_from_risk": "{hazard}ৰ পৰা বৰ্তমানৰ {level} বিপদৰ ভিত্তিত।",
        "ri_umbrella_title": "ছাতি",
        "ri_umbrella_yes": "ছাতি লওক",
        "ri_umbrella_maybe": "ছাতি ৰখা ভাল",
        "ri_umbrella_no": "ছাতিৰ প্ৰয়োজন নাই",
        "ri_umbrella_prob": "অহা 12 ঘণ্টাত বৰষুণৰ সম্ভাৱনা প্ৰায় {prob}% লৈ যায়।",
        "ri_umbrella_mm": "24 ঘণ্টাত প্ৰায় {mm} মি.মি. বৰষুণ হ'ব পাৰে।",
        "ri_comfort_title": "আৰাম",
        "ri_comfort_hot": "গৰম — পানী খাই থাকক",
        "ri_comfort_muggy": "গৰম আৰু আৰ্দ্ৰ",
        "ri_comfort_warm": "গৰম",
        "ri_comfort_cool": "ঠাণ্ডা",
        "ri_comfort_ok": "আৰামদায়ক",
        "ri_comfort_detail": "{hum}% আৰ্দ্ৰতাত {feels}°C যেন লাগে।",
        "ri_comfort_detail_temp": "{feels}°C যেন লাগে।",
        "ri_outdoor_title": "বাহিৰলৈ ওলোৱা",
        "ri_outdoor_avoid": "বহু সময় বাহিৰত থকা এৰাওক",
        "ri_outdoor_caution": "সাৱধানে বাহিৰলৈ যাওক",
        "ri_outdoor_good": "বাহিৰৰ কামৰ বাবে ভাল",
        "ri_rain_title": "বৰষুণৰ প্ৰভাৱ",
        "ri_rain_high": "বেছি",
        "ri_rain_moderate": "মজলীয়া",
        "ri_rain_low": "কম",
        "ri_rain_detail_mm": "অহা 24 ঘণ্টাত প্ৰায় {mm} মি.মি. হ'ব পাৰে।",
        "ri_rain_detail_prob": "অহা 12 ঘণ্টাত বৰষুণৰ সম্ভাৱনা প্ৰায় {prob}% লৈ যায়।",
        "ri_irrigation_title": "জলসিঞ্চনৰ পৰামৰ্শ",
        "ri_irrigation_nodata": "জলসিঞ্চনৰ পৰামৰ্শৰ বাবে পৰ্যাপ্ত বৰষুণৰ তথ্য নাই",
        "ri_irrigation_delay": "জলসিঞ্চন পিছুৱাই দিয়াৰ কথা ভাবক",
        "ri_irrigation_delay_detail": "অহা 24 ঘণ্টাত প্ৰায় {mm} মি.মি. বৰষুণ হ'ব পাৰে।",
        "ri_irrigation_needed": "জলসিঞ্চনৰ প্ৰয়োজন হ'ব পাৰে",
        "ri_irrigation_dry_detail": "পূৰ্বাভাসৰ সময়ত বৰষুণ অতি কম বা নাই।",
        "ri_irrigation_monitor": "অৱস্থাৰ ওপৰত চকু ৰাখক",
        "ri_irrigation_monitor_detail": "প্ৰায় {mm} মি.মি. হ'ব পাৰে — পাতল, পৰ্যাপ্ত নহ'বও পাৰে।",
        "ri_crop_title": "শস্যৰ ওপৰত বতৰৰ বিপদ",
        "ri_crop_high": "বেছি",
        "ri_crop_moderate": "মজলীয়া",
        "ri_crop_low": "কম",
        "ri_crop_high_detail": "{hum}% আৰ্দ্ৰতাৰ গৰম, তিতা বতাহ এনে অৱস্থা য'ত ছত্ৰাকজনিত সমস্যাৰ সম্ভাৱনা বাঢ়ে। বৰষুণৰ পিছত শস্য চোৱাৰ কথা ভাবক।",
        "ri_crop_moderate_detail": "আৰ্দ্ৰতা {hum}%। বৰষুণৰ পিছত চকু ৰখা উপযোগী হ'ব পাৰে।",
        "ri_crop_low_detail": "আৰ্দ্ৰতা {hum}% — সাধাৰণতে চিন্তা বঢ়োৱা মাত্ৰাতকৈ কম।",
        "ri_field_title": "আজিৰ পথাৰৰ পৰামৰ্শ",
        "ri_field_storm": "ধুমুহাৰ সম্ভাৱনা আছে। পথাৰৰ কাম পিছুৱাই সঁজুলি সুৰক্ষিত ৰখাৰ কথা ভাবক।",
        "ri_field_rain": "প্ৰায় {mm} মি.মি. বৰষুণ হ'ব পাৰে। পানী দিয়াৰ আগতে পথাৰৰ তিতা চোৱাৰ কথা ভাবক।",
        "ri_field_humid": "আৰ্দ্ৰতা {hum}% হৈ বেছি। তিতাজনিত সমস্যাৰ বাবে শস্যত চকু ৰখা উপযোগী হ'ব পাৰে।",
        "ri_field_hot": "প্ৰায় {feels}°C যেন লাগিব। মাটিৰ তিতা চাই ৰাতিপুৱা বা আবেলি পানী দিয়াৰ কথা ভাবক।",
        "ri_field_clear": "ডাঙৰ বতৰৰ সলনি দেখা নাযায়। পথাৰৰ কামৰ বাবে উপযুক্ত সময়।",
        "ri_fishing_title": "মাছ ধৰাৰ অৱস্থা",
        "ri_fishing_avoid": "এৰাওক",
        "ri_fishing_caution": "সাৱধান",
        "ri_fishing_favorable": "অনুকূল",
        "ri_fishing_detail": "কেৱল বতৰৰ ভিত্তিত। ওলোৱাৰ আগতে চৰকাৰী সাগৰীয় সতৰ্কবাণী চাওক।",
        "ri_wind_title": "বতাহ",
        "ri_wind_gust": "দমকা প্ৰায় {gust} কি.মি./ঘণ্টা লৈ।",
        "ri_storm_title": "বিজুলী আৰু ধুমুহাৰ বিপদ",
        "ri_storm_high": "বেছি",
        "ri_storm_moderate": "মজলীয়া",
        "ri_storm_low": "কম",
        "ri_storm_high_detail": "ধুমুহাৰ সম্ভাৱনা বেছি। ওলোৱাৰ আগতে চৰকাৰী সতৰ্কবাণী চাওক।",
        "ri_storm_moderate_detail": "ধুমুহা হ'ব পাৰে। ওলোৱাৰ আগতে চৰকাৰী সতৰ্কবাণী চাওক।",
        "ri_storm_low_detail": "এতিয়া ধুমুহাৰ কোনো সংকেত নাই।",
        "ri_visibility_title": "দৃশ্যমানতা",
        # Named contributors, shared by the travel and commute readings.
        "ri_factor_rain": "বৰষুণ",
        "ri_factor_visibility": "কম দৃশ্যমানতা",
        "ri_factor_wind": "প্ৰবল বতাহ",
        "ri_factor_storm": "ধুমুহা",
        "ri_trip_title": "ভ্ৰমণৰ বতৰ",
        "ri_trip_tomorrow": "কাইলৈ: বৰষুণৰ সম্ভাৱনা প্ৰায় {prob}%।",
        "ri_trip_tomorrow_cond": "কাইলৈ: {cond}।",
        "ri_travel_title": "ভ্ৰমণৰ বিপদ",
        "ri_travel_high": "বেছি",
        "ri_travel_moderate": "মজলীয়া",
        "ri_travel_low": "কম",
        "ri_travel_factors": "কাৰণ: {factors}।",
        "ri_travel_clear": "এতিয়া কোনো বতৰৰ কাৰণ ভ্ৰমণৰ বিপক্ষে নাই।",
        "ri_activity_title": "বাহিৰৰ কাম",
        "ri_activity_poor": "উপযুক্ত নহয়",
        "ri_activity_caution": "সাৱধান হওক",
        "ri_activity_good": "ভাল",
        "ri_activity_excellent": "অতি ভাল",
        "ri_pack_title": "লগত কি লব",
        "ri_pack_umbrella": "ছাতি",
        "ri_pack_raincoat": "ৰেইন জেকেট",
        "ri_pack_water": "পানী",
        "ri_pack_sun": "ৰ'দৰ পৰা সুৰক্ষা",
        "ri_pack_layer": "গৰম কাপোৰ",
        "ri_pack_windproof": "বতাহ ৰোধী কাপোৰ",
        "ri_pack_nothing": "বতৰৰ বাবে বিশেষ একো নালাগে",
        "ri_commute_title": "যাতায়াতৰ বিপদ",
        "ri_commute_high": "বেছি",
        "ri_commute_moderate": "মজলীয়া",
        "ri_commute_low": "কম",
        "ri_commute_detail": "কেৱল বতৰৰ বিপদ — ইয়াত যান-জঁট ধৰা হোৱা নাই।",
        "ri_hazards_title": "বতৰৰ বিপদ",
        "ri_hazards_none": "একো পোৱা নগ'ল",
        "ri_departure_title": "আটাইতকৈ শান্ত সময়",
        "ri_departure_detail": "অহা যাতায়াতৰ সময়ত আটাইতকৈ কম বতৰৰ বিপদ।",
        "ri_reminder_title": "মনত ৰাখক",
        "ri_reminder_storm": "ধুমুহাৰ সম্ভাৱনা আছে — অলপ অতিৰিক্ত সময় ৰাখক।",
        "ri_reminder_rain": "ছাতি লওক আৰু অলপ অতিৰিক্ত সময় ৰাখক।",
        "ri_reminder_wind": "প্ৰবল বতাহৰ সম্ভাৱনা — মুকলি ৰাস্তাত সাৱধান হওক।",
        "ri_reminder_clear": "আপোনাৰ যাতায়াতৰ বাবে বতৰ অনুকূল দেখা গৈছে।",
        # --- Map insight: one line per forecast hour ------------------
        "mi_rain_high": "{time} মান বৰষুণৰ সম্ভাৱনা আছে, প্ৰায় {prob}%।",
        "mi_rain_rising": "{time} লৈ বৰষুণৰ সম্ভাৱনা বাঢ়ি প্ৰায় {prob}% হয়।",
        "mi_rain_easing": "{time} লৈ বৰষুণৰ সম্ভাৱনা কমি প্ৰায় {prob}% হয়।",
        "mi_storm": "{time} মান বতৰৰ বিপদ {level}।",
        "mi_wind": "{time} লৈ বতাহ বাঢ়ি প্ৰায় {wind} কি.মি./ঘণ্টা হয়।",
        "mi_calm": "{time} মান ডাঙৰ বতৰৰ সলনি দেখা নাযায়।",
        "mi_role_general": "সেই সময়ত বাহিৰলৈ ওলালে ছাতি লওক।",
        "mi_role_general_calm": "বাহিৰত থকাৰ বাবে ভাল সময়।",
        "mi_role_farmer": "পানী দিয়াৰ আগতে পথাৰৰ তিতা চোৱাৰ কথা ভাবক।",
        "mi_role_farmer_calm": "পথাৰৰ কামৰ বাবে উপযুক্ত সময়।",
        "mi_role_fisherman": "ওলোৱাৰ আগতে চৰকাৰী সতৰ্কবাণী চাওক।",
        "mi_role_fisherman_calm": "তথাপি ওলোৱাৰ আগতে চৰকাৰী সাগৰীয় সতৰ্কবাণী চাওক।",
        "mi_role_traveler": "বাহিৰৰ কাম দিনৰ আগফালে কৰাৰ কথা ভাবক।",
        "mi_role_traveler_calm": "বাহিৰৰ পৰিকল্পনাৰ বাবে উপযুক্ত।",
        "mi_role_commuter": "সম্ভৱ হলে আগতে ওলোৱাৰ কথা ভাবক।",
        "mi_role_commuter_calm": "আপোনাৰ যাতায়াতৰ বাবে পৰিষ্কাৰ সময়।",
    },
}


# The nine-role selector added five readers. Their wording lives here rather
# than inline above so the six language blocks stay diffable side by side, and
# so a missing translation is a visible hole rather than a silent English
# fallback buried in a 900-line literal.
ROLE_SENTENCES_EXTRA: dict[str, dict[str, str]] = {
    # -----------------------------------------------------------------------
    "en": {
        "ri_heading_driver": "Driving intelligence",
        "ri_heading_outdoor_worker": "Site weather intelligence",
        "ri_heading_household": "Home weather intelligence",
        "ri_heading_student": "Study-day intelligence",
        "ri_heading_caregiver": "Care and community intelligence",
        # Driver
        "ri_road_vis_title": "Road visibility",
        "ri_road_vis_poor": "Poor — slow right down",
        "ri_road_vis_reduced": "Reduced",
        "ri_road_vis_clear": "Clear",
        "ri_road_vis_detail": "Visibility is around {km} km.",
        "ri_road_surface_title": "Road surface",
        "ri_road_surface_standing": "Standing water likely",
        "ri_road_surface_wet": "Wet roads expected",
        "ri_road_surface_dry": "Dry roads expected",
        "ri_road_surface_detail": "Braking distance grows on a wet surface.",
        "ri_crosswind_title": "Crosswind",
        "ri_crosswind_strong": "Strong — expect buffeting",
        "ri_crosswind_brisk": "Noticeable on open stretches",
        "ri_crosswind_calm": "Light",
        # Outdoor worker
        "ri_heatstress_title": "Heat stress",
        "ri_heatstress_high": "High — shorten work spells",
        "ri_heatstress_moderate": "Moderate — take shade breaks",
        "ri_heatstress_ok": "Manageable",
        "ri_workwindow_title": "Easiest working window",
        "ri_workwindow_detail": "The lowest-risk daylight hour in the forecast.",
        "ri_workwindow_none": "No hourly forecast for today",
        # Household
        "ri_home_rain_title": "Washing and drying",
        "ri_home_rain_wet": "Keep the washing indoors",
        "ri_home_rain_maybe": "Drying may be interrupted",
        "ri_home_rain_dry": "Good drying conditions",
        "ri_prepare_title": "Home preparedness",
        "ri_prepare_high": "Charge phones and keep a torch ready",
        "ri_prepare_watch": "Worth having a torch to hand",
        "ri_prepare_normal": "Nothing extra needed",
        "ri_prepare_detail": "Power interruptions tend to arrive with the weather, not after it.",
        # Caregiver
        "ri_vulnerable_title": "Vulnerable people",
        "ri_vulnerable_heat": "Heat risk — check in more often",
        "ri_vulnerable_cold": "Cool — keep the very young and old warm",
        "ri_vulnerable_ok": "Comfortable for most",
        "ri_exposure_title": "Exposure outdoors",
        "ri_exposure_high": "Keep outdoor time short",
        "ri_exposure_some": "Some exposure risk",
        "ri_exposure_low": "Low",
        "ri_exposure_detail": "Rain and wind reach those who move slowly first.",
        # Map interpretation
        "mi_role_driver": "Consider allowing extra time and distance on the road.",
        "mi_role_driver_calm": "A clear stretch for driving.",
        "mi_role_outdoor_worker": "Consider bringing heavy work forward or pausing it.",
        "mi_role_outdoor_worker_calm": "A workable window on site.",
        "mi_role_household": "Consider bringing washing in before then.",
        "mi_role_household_calm": "A good window for outdoor chores.",
        "mi_role_student": "Consider leaving for class earlier than usual.",
        "mi_role_student_calm": "A clear window for the journey.",
        "mi_role_caregiver": "Consider checking on anyone who cannot move quickly.",
        "mi_role_caregiver_calm": "A settled window for outdoor visits.",
    },
    # -----------------------------------------------------------------------
    "hi": {
        "ri_heading_driver": "गाड़ी चलाने की मौसम जानकारी",
        "ri_heading_outdoor_worker": "काम-स्थल की मौसम जानकारी",
        "ri_heading_household": "घर की मौसम जानकारी",
        "ri_heading_student": "पढ़ाई के दिन की मौसम जानकारी",
        "ri_heading_caregiver": "देखभाल और समुदाय की मौसम जानकारी",
        "ri_road_vis_title": "सड़क पर दृश्यता",
        "ri_road_vis_poor": "ख़राब — गति काफ़ी घटाएँ",
        "ri_road_vis_reduced": "कम",
        "ri_road_vis_clear": "साफ़",
        "ri_road_vis_detail": "दृश्यता लगभग {km} किमी है।",
        "ri_road_surface_title": "सड़क की सतह",
        "ri_road_surface_standing": "पानी भरने की संभावना",
        "ri_road_surface_wet": "सड़कें गीली रहने की संभावना",
        "ri_road_surface_dry": "सड़कें सूखी रहने की संभावना",
        "ri_road_surface_detail": "गीली सतह पर ब्रेक लगने की दूरी बढ़ जाती है।",
        "ri_crosswind_title": "बग़ली हवा",
        "ri_crosswind_strong": "तेज़ — झटके लग सकते हैं",
        "ri_crosswind_brisk": "खुले हिस्सों में महसूस होगी",
        "ri_crosswind_calm": "हल्की",
        "ri_heatstress_title": "गर्मी का दबाव",
        "ri_heatstress_high": "अधिक — काम के अंतराल छोटे रखें",
        "ri_heatstress_moderate": "मध्यम — छाया में विराम लें",
        "ri_heatstress_ok": "सँभालने लायक",
        "ri_workwindow_title": "काम के लिए सबसे आसान समय",
        "ri_workwindow_detail": "पूर्वानुमान में दिन का सबसे कम जोखिम वाला घंटा।",
        "ri_workwindow_none": "आज के लिए घंटेवार पूर्वानुमान नहीं",
        "ri_home_rain_title": "कपड़े धोना और सुखाना",
        "ri_home_rain_wet": "कपड़े अंदर ही रखें",
        "ri_home_rain_maybe": "सूखने में रुकावट आ सकती है",
        "ri_home_rain_dry": "सुखाने के लिए अच्छा दिन",
        "ri_prepare_title": "घर की तैयारी",
        "ri_prepare_high": "फ़ोन चार्ज रखें और टॉर्च तैयार रखें",
        "ri_prepare_watch": "टॉर्च पास रखना ठीक रहेगा",
        "ri_prepare_normal": "अलग से कुछ ज़रूरी नहीं",
        "ri_prepare_detail": "बिजली आमतौर पर मौसम के साथ ही जाती है, बाद में नहीं।",
        "ri_vulnerable_title": "कमज़ोर लोग",
        "ri_vulnerable_heat": "गर्मी का ख़तरा — बार-बार हाल लें",
        "ri_vulnerable_cold": "ठंडक — बच्चों और बुज़ुर्गों को गर्म रखें",
        "ri_vulnerable_ok": "अधिकतर के लिए आरामदेह",
        "ri_exposure_title": "बाहर रहने का असर",
        "ri_exposure_high": "बाहर का समय कम रखें",
        "ri_exposure_some": "कुछ ख़तरा है",
        "ri_exposure_low": "कम",
        "ri_exposure_detail": "बारिश और हवा सबसे पहले धीरे चलने वालों तक पहुँचती है।",
        "mi_role_driver": "सड़क पर अतिरिक्त समय और दूरी रखने पर विचार करें।",
        "mi_role_driver_calm": "गाड़ी चलाने के लिए साफ़ समय।",
        "mi_role_outdoor_worker": "भारी काम पहले करने या रोकने पर विचार करें।",
        "mi_role_outdoor_worker_calm": "साइट पर काम लायक समय।",
        "mi_role_household": "उससे पहले कपड़े अंदर ले लेने पर विचार करें।",
        "mi_role_household_calm": "बाहरी कामों के लिए अच्छा समय।",
        "mi_role_student": "कक्षा के लिए सामान्य से जल्दी निकलने पर विचार करें।",
        "mi_role_student_calm": "सफ़र के लिए साफ़ समय।",
        "mi_role_caregiver": "जो जल्दी हिल-डुल नहीं सकते उनका हाल लेने पर विचार करें।",
        "mi_role_caregiver_calm": "बाहर मिलने-जुलने के लिए शांत समय।",
    },
    # -----------------------------------------------------------------------
    "te": {
        "ri_heading_driver": "డ్రైవింగ్ వాతావరణ సమాచారం",
        "ri_heading_outdoor_worker": "పని ప్రదేశ వాతావరణ సమాచారం",
        "ri_heading_household": "ఇంటి వాతావరణ సమాచారం",
        "ri_heading_student": "చదువు రోజు వాతావరణ సమాచారం",
        "ri_heading_caregiver": "సంరక్షణ, సమాజ వాతావరణ సమాచారం",
        "ri_road_vis_title": "రోడ్డుపై దృశ్యత",
        "ri_road_vis_poor": "తక్కువ — వేగం బాగా తగ్గించండి",
        "ri_road_vis_reduced": "తగ్గింది",
        "ri_road_vis_clear": "స్పష్టం",
        "ri_road_vis_detail": "దృశ్యత సుమారు {km} కి.మీ.",
        "ri_road_surface_title": "రోడ్డు ఉపరితలం",
        "ri_road_surface_standing": "నీరు నిలిచే అవకాశం",
        "ri_road_surface_wet": "రోడ్లు తడిగా ఉండవచ్చు",
        "ri_road_surface_dry": "రోడ్లు పొడిగా ఉండవచ్చు",
        "ri_road_surface_detail": "తడి ఉపరితలంపై బ్రేక్ దూరం పెరుగుతుంది.",
        "ri_crosswind_title": "పక్క గాలి",
        "ri_crosswind_strong": "బలంగా — వాహనం ఊగవచ్చు",
        "ri_crosswind_brisk": "బహిరంగ ప్రాంతాల్లో తెలుస్తుంది",
        "ri_crosswind_calm": "తేలికగా",
        "ri_heatstress_title": "వేడి ఒత్తిడి",
        "ri_heatstress_high": "ఎక్కువ — పని విడతలు తగ్గించండి",
        "ri_heatstress_moderate": "మధ్యస్థం — నీడలో విరామం తీసుకోండి",
        "ri_heatstress_ok": "తట్టుకోగలిగేది",
        "ri_workwindow_title": "పనికి సులభమైన సమయం",
        "ri_workwindow_detail": "సూచనలో పగటిపూట అత్యల్ప ప్రమాద గంట.",
        "ri_workwindow_none": "ఈరోజుకు గంటల వారీ సూచన లేదు",
        "ri_home_rain_title": "బట్టలు ఉతకడం, ఆరబెట్టడం",
        "ri_home_rain_wet": "బట్టలు లోపలే ఉంచండి",
        "ri_home_rain_maybe": "ఆరడం మధ్యలో ఆగవచ్చు",
        "ri_home_rain_dry": "ఆరబెట్టడానికి మంచి రోజు",
        "ri_prepare_title": "ఇంటి సన్నద్ధత",
        "ri_prepare_high": "ఫోన్లు చార్జ్ చేసి, టార్చి సిద్ధంగా ఉంచండి",
        "ri_prepare_watch": "టార్చి చేతికి అందుబాటులో ఉంచడం మంచిది",
        "ri_prepare_normal": "అదనంగా ఏమీ అవసరం లేదు",
        "ri_prepare_detail": "కరెంటు సాధారణంగా వాతావరణంతో పాటే పోతుంది, తర్వాత కాదు.",
        "ri_vulnerable_title": "బలహీనులు",
        "ri_vulnerable_heat": "వేడి ప్రమాదం — తరచూ చూస్తూ ఉండండి",
        "ri_vulnerable_cold": "చల్లగా — పిల్లలను, వృద్ధులను వెచ్చగా ఉంచండి",
        "ri_vulnerable_ok": "చాలామందికి సౌకర్యంగా",
        "ri_exposure_title": "బయట ఉండటం",
        "ri_exposure_high": "బయట గడిపే సమయం తగ్గించండి",
        "ri_exposure_some": "కొంత ప్రమాదం ఉంది",
        "ri_exposure_low": "తక్కువ",
        "ri_exposure_detail": "వర్షం, గాలి ముందుగా నెమ్మదిగా కదిలేవారినే తాకుతాయి.",
        "mi_role_driver": "రోడ్డుపై అదనపు సమయం, దూరం ఉంచడాన్ని పరిశీలించండి.",
        "mi_role_driver_calm": "డ్రైవింగ్‌కు స్పష్టమైన సమయం.",
        "mi_role_outdoor_worker": "బరువైన పనిని ముందుకు జరపడం లేదా ఆపడం పరిశీలించండి.",
        "mi_role_outdoor_worker_calm": "సైట్‌లో పనికి అనువైన సమయం.",
        "mi_role_household": "అంతకుముందే బట్టలు లోపలికి తీసుకోవడాన్ని పరిశీలించండి.",
        "mi_role_household_calm": "బయటి ఇంటి పనులకు మంచి సమయం.",
        "mi_role_student": "తరగతికి మామూలు కంటే ముందే బయలుదేరడాన్ని పరిశీలించండి.",
        "mi_role_student_calm": "ప్రయాణానికి స్పష్టమైన సమయం.",
        "mi_role_caregiver": "త్వరగా కదల్లేని వారిని చూసుకోవడాన్ని పరిశీలించండి.",
        "mi_role_caregiver_calm": "బయటి సందర్శనలకు నిలకడైన సమయం.",
    },
    # -----------------------------------------------------------------------
    "bn": {
        "ri_heading_driver": "গাড়ি চালানোর আবহাওয়া তথ্য",
        "ri_heading_outdoor_worker": "কর্মস্থলের আবহাওয়া তথ্য",
        "ri_heading_household": "ঘরের আবহাওয়া তথ্য",
        "ri_heading_student": "পড়াশোনার দিনের আবহাওয়া তথ্য",
        "ri_heading_caregiver": "সেবা ও সমাজের আবহাওয়া তথ্য",
        "ri_road_vis_title": "রাস্তায় দৃশ্যমানতা",
        "ri_road_vis_poor": "খারাপ — গতি অনেক কমান",
        "ri_road_vis_reduced": "কম",
        "ri_road_vis_clear": "পরিষ্কার",
        "ri_road_vis_detail": "দৃশ্যমানতা প্রায় {km} কিমি।",
        "ri_road_surface_title": "রাস্তার পৃষ্ঠ",
        "ri_road_surface_standing": "জল জমার সম্ভাবনা",
        "ri_road_surface_wet": "রাস্তা ভেজা থাকতে পারে",
        "ri_road_surface_dry": "রাস্তা শুকনো থাকতে পারে",
        "ri_road_surface_detail": "ভেজা পৃষ্ঠে ব্রেক করার দূরত্ব বেড়ে যায়।",
        "ri_crosswind_title": "পাশের বাতাস",
        "ri_crosswind_strong": "জোরালো — ঝাঁকুনি লাগতে পারে",
        "ri_crosswind_brisk": "খোলা অংশে টের পাওয়া যাবে",
        "ri_crosswind_calm": "হালকা",
        "ri_heatstress_title": "গরমের চাপ",
        "ri_heatstress_high": "বেশি — কাজের পালা ছোট রাখুন",
        "ri_heatstress_moderate": "মাঝারি — ছায়ায় বিরতি নিন",
        "ri_heatstress_ok": "সামলানো যায়",
        "ri_workwindow_title": "কাজের সবচেয়ে সহজ সময়",
        "ri_workwindow_detail": "পূর্বাভাসে দিনের সবচেয়ে কম ঝুঁকির ঘণ্টা।",
        "ri_workwindow_none": "আজকের জন্য ঘণ্টাভিত্তিক পূর্বাভাস নেই",
        "ri_home_rain_title": "কাপড় কাচা ও শুকানো",
        "ri_home_rain_wet": "কাপড় ভিতরেই রাখুন",
        "ri_home_rain_maybe": "শুকানোয় বাধা পড়তে পারে",
        "ri_home_rain_dry": "শুকানোর জন্য ভালো দিন",
        "ri_prepare_title": "ঘরের প্রস্তুতি",
        "ri_prepare_high": "ফোন চার্জ দিন ও টর্চ প্রস্তুত রাখুন",
        "ri_prepare_watch": "টর্চ হাতের কাছে রাখা ভালো",
        "ri_prepare_normal": "বাড়তি কিছু লাগবে না",
        "ri_prepare_detail": "বিদ্যুৎ সাধারণত আবহাওয়ার সঙ্গেই যায়, পরে নয়।",
        "ri_vulnerable_title": "ঝুঁকিপ্রবণ মানুষ",
        "ri_vulnerable_heat": "গরমের ঝুঁকি — ঘন ঘন খোঁজ নিন",
        "ri_vulnerable_cold": "ঠান্ডা — শিশু ও বয়স্কদের গরম রাখুন",
        "ri_vulnerable_ok": "বেশির ভাগের জন্য আরামদায়ক",
        "ri_exposure_title": "বাইরে থাকার প্রভাব",
        "ri_exposure_high": "বাইরের সময় কম রাখুন",
        "ri_exposure_some": "কিছুটা ঝুঁকি আছে",
        "ri_exposure_low": "কম",
        "ri_exposure_detail": "বৃষ্টি ও বাতাস আগে তাঁদেরই ছোঁয় যাঁরা ধীরে চলেন।",
        "mi_role_driver": "রাস্তায় বাড়তি সময় ও দূরত্ব রাখার কথা ভাবুন।",
        "mi_role_driver_calm": "গাড়ি চালানোর জন্য পরিষ্কার সময়।",
        "mi_role_outdoor_worker": "ভারী কাজ এগিয়ে আনা বা থামানোর কথা ভাবুন।",
        "mi_role_outdoor_worker_calm": "সাইটে কাজের উপযোগী সময়।",
        "mi_role_household": "তার আগে কাপড় ভিতরে আনার কথা ভাবুন।",
        "mi_role_household_calm": "বাইরের ঘরকন্নার জন্য ভালো সময়।",
        "mi_role_student": "ক্লাসের জন্য রোজকার চেয়ে আগে বেরোনোর কথা ভাবুন।",
        "mi_role_student_calm": "যাত্রার জন্য পরিষ্কার সময়।",
        "mi_role_caregiver": "যাঁরা দ্রুত নড়তে পারেন না তাঁদের খোঁজ নেওয়ার কথা ভাবুন।",
        "mi_role_caregiver_calm": "বাইরে দেখা করার জন্য শান্ত সময়।",
    },
    # -----------------------------------------------------------------------
    "mr": {
        "ri_heading_driver": "वाहन चालवण्याची हवामान माहिती",
        "ri_heading_outdoor_worker": "कामाच्या जागेची हवामान माहिती",
        "ri_heading_household": "घरची हवामान माहिती",
        "ri_heading_student": "अभ्यासाच्या दिवसाची हवामान माहिती",
        "ri_heading_caregiver": "काळजी व समुदायाची हवामान माहिती",
        "ri_road_vis_title": "रस्त्यावरील दृश्यमानता",
        "ri_road_vis_poor": "खराब — वेग बराच कमी करा",
        "ri_road_vis_reduced": "कमी",
        "ri_road_vis_clear": "स्वच्छ",
        "ri_road_vis_detail": "दृश्यमानता सुमारे {km} किमी आहे.",
        "ri_road_surface_title": "रस्त्याचा पृष्ठभाग",
        "ri_road_surface_standing": "पाणी साचण्याची शक्यता",
        "ri_road_surface_wet": "रस्ते ओले राहण्याची शक्यता",
        "ri_road_surface_dry": "रस्ते कोरडे राहण्याची शक्यता",
        "ri_road_surface_detail": "ओल्या पृष्ठभागावर ब्रेकचे अंतर वाढते.",
        "ri_crosswind_title": "बाजूचा वारा",
        "ri_crosswind_strong": "जोरदार — गाडी हलू शकते",
        "ri_crosswind_brisk": "मोकळ्या भागात जाणवेल",
        "ri_crosswind_calm": "हलका",
        "ri_heatstress_title": "उष्णतेचा ताण",
        "ri_heatstress_high": "जास्त — कामाचे टप्पे लहान ठेवा",
        "ri_heatstress_moderate": "मध्यम — सावलीत विश्रांती घ्या",
        "ri_heatstress_ok": "सहन होण्याजोगा",
        "ri_workwindow_title": "कामासाठी सर्वात सोपी वेळ",
        "ri_workwindow_detail": "अंदाजातील दिवसाचा सर्वात कमी धोक्याचा तास.",
        "ri_workwindow_none": "आजसाठी तासवार अंदाज नाही",
        "ri_home_rain_title": "कपडे धुणे व वाळवणे",
        "ri_home_rain_wet": "कपडे आतच ठेवा",
        "ri_home_rain_maybe": "वाळण्यात अडथळा येऊ शकतो",
        "ri_home_rain_dry": "वाळवण्यासाठी चांगला दिवस",
        "ri_prepare_title": "घराची तयारी",
        "ri_prepare_high": "फोन चार्ज ठेवा आणि टॉर्च तयार ठेवा",
        "ri_prepare_watch": "टॉर्च जवळ ठेवणे बरे",
        "ri_prepare_normal": "वेगळे काही लागणार नाही",
        "ri_prepare_detail": "वीज सहसा हवामानासोबतच जाते, नंतर नाही.",
        "ri_vulnerable_title": "असुरक्षित व्यक्ती",
        "ri_vulnerable_heat": "उष्णतेचा धोका — वारंवार विचारपूस करा",
        "ri_vulnerable_cold": "थंडी — मुलांना व वृद्धांना उबदार ठेवा",
        "ri_vulnerable_ok": "बहुतेकांसाठी आरामदायी",
        "ri_exposure_title": "बाहेर राहण्याचा परिणाम",
        "ri_exposure_high": "बाहेरचा वेळ कमी ठेवा",
        "ri_exposure_some": "काही प्रमाणात धोका",
        "ri_exposure_low": "कमी",
        "ri_exposure_detail": "पाऊस व वारा आधी हळू चालणाऱ्यांपर्यंत पोहोचतो.",
        "mi_role_driver": "रस्त्यावर जादा वेळ व अंतर ठेवण्याचा विचार करा.",
        "mi_role_driver_calm": "वाहन चालवण्यासाठी मोकळा वेळ.",
        "mi_role_outdoor_worker": "जड काम आधी करण्याचा किंवा थांबवण्याचा विचार करा.",
        "mi_role_outdoor_worker_calm": "साइटवर कामासाठी योग्य वेळ.",
        "mi_role_household": "त्याआधी कपडे आत घेण्याचा विचार करा.",
        "mi_role_household_calm": "बाहेरील घरकामासाठी चांगला वेळ.",
        "mi_role_student": "वर्गासाठी नेहमीपेक्षा लवकर निघण्याचा विचार करा.",
        "mi_role_student_calm": "प्रवासासाठी मोकळा वेळ.",
        "mi_role_caregiver": "पटकन हालचाल न करू शकणाऱ्यांची विचारपूस करण्याचा विचार करा.",
        "mi_role_caregiver_calm": "बाहेर भेटीगाठीसाठी शांत वेळ.",
    },
    # -----------------------------------------------------------------------
    "as": {
        "ri_heading_driver": "গাড়ী চলোৱাৰ বতৰৰ তথ্য",
        "ri_heading_outdoor_worker": "কৰ্মস্থলীৰ বতৰৰ তথ্য",
        "ri_heading_household": "ঘৰৰ বতৰৰ তথ্য",
        "ri_heading_student": "পঢ়াৰ দিনৰ বতৰৰ তথ্য",
        "ri_heading_caregiver": "যত্ন আৰু সমাজৰ বতৰৰ তথ্য",
        "ri_road_vis_title": "ৰাস্তাৰ দৃশ্যমানতা",
        "ri_road_vis_poor": "বেয়া — গতি বহুত কমাওক",
        "ri_road_vis_reduced": "কম",
        "ri_road_vis_clear": "পৰিষ্কাৰ",
        "ri_road_vis_detail": "দৃশ্যমানতা প্ৰায় {km} কিমি।",
        "ri_road_surface_title": "ৰাস্তাৰ পৃষ্ঠ",
        "ri_road_surface_standing": "পানী জমা হোৱাৰ সম্ভাৱনা",
        "ri_road_surface_wet": "ৰাস্তা তিতি থাকিব পাৰে",
        "ri_road_surface_dry": "ৰাস্তা শুকান থাকিব পাৰে",
        "ri_road_surface_detail": "তিতা পৃষ্ঠত ব্ৰেকৰ দূৰত্ব বাঢ়ে।",
        "ri_crosswind_title": "কাষৰ বতাহ",
        "ri_crosswind_strong": "প্ৰবল — জোকাৰণি লাগিব পাৰে",
        "ri_crosswind_brisk": "মুকলি অংশত গম পোৱা যাব",
        "ri_crosswind_calm": "পাতল",
        "ri_heatstress_title": "গৰমৰ চাপ",
        "ri_heatstress_high": "বেছি — কামৰ পালা চুটি ৰাখক",
        "ri_heatstress_moderate": "মধ্যম — ছাঁত জিৰণি লওক",
        "ri_heatstress_ok": "সহনীয়",
        "ri_workwindow_title": "কামৰ বাবে আটাইতকৈ সহজ সময়",
        "ri_workwindow_detail": "পূৰ্বাভাসত দিনটোৰ আটাইতকৈ কম বিপদৰ ঘণ্টা।",
        "ri_workwindow_none": "আজিৰ বাবে ঘণ্টাভিত্তিক পূৰ্বাভাস নাই",
        "ri_home_rain_title": "কাপোৰ ধোৱা আৰু শুকুৱা",
        "ri_home_rain_wet": "কাপোৰ ভিতৰতে ৰাখক",
        "ri_home_rain_maybe": "শুকুৱাত বাধা পৰিব পাৰে",
        "ri_home_rain_dry": "শুকুৱাবলৈ ভাল দিন",
        "ri_prepare_title": "ঘৰৰ প্ৰস্তুতি",
        "ri_prepare_high": "ফোন চাৰ্জ কৰক আৰু টৰ্চ সাজু ৰাখক",
        "ri_prepare_watch": "টৰ্চ ওচৰত ৰখাটো ভাল",
        "ri_prepare_normal": "অতিৰিক্ত একো নালাগে",
        "ri_prepare_detail": "বিদ্যুৎ সাধাৰণতে বতৰৰ লগতেই যায়, পিছত নহয়।",
        "ri_vulnerable_title": "দুৰ্বল লোকসকল",
        "ri_vulnerable_heat": "গৰমৰ বিপদ — সঘনাই খবৰ লওক",
        "ri_vulnerable_cold": "ঠাণ্ডা — শিশু আৰু বৃদ্ধসকলক গৰম ৰাখক",
        "ri_vulnerable_ok": "বেছিভাগৰ বাবে আৰামদায়ক",
        "ri_exposure_title": "বাহিৰত থকাৰ প্ৰভাৱ",
        "ri_exposure_high": "বাহিৰৰ সময় কম ৰাখক",
        "ri_exposure_some": "কিছু বিপদ আছে",
        "ri_exposure_low": "কম",
        "ri_exposure_detail": "বৰষুণ আৰু বতাহে আগতে লাহে লাহে খোজ কঢ়াসকলকেই স্পৰ্শ কৰে।",
        "mi_role_driver": "ৰাস্তাত অতিৰিক্ত সময় আৰু দূৰত্ব ৰখাৰ কথা ভাবক।",
        "mi_role_driver_calm": "গাড়ী চলাবলৈ পৰিষ্কাৰ সময়।",
        "mi_role_outdoor_worker": "গধুৰ কাম আগতে কৰা বা বন্ধ কৰাৰ কথা ভাবক।",
        "mi_role_outdoor_worker_calm": "ছাইটত কামৰ বাবে উপযুক্ত সময়।",
        "mi_role_household": "তাৰ আগতে কাপোৰ ভিতৰলৈ অনাৰ কথা ভাবক।",
        "mi_role_household_calm": "বাহিৰৰ ঘৰুৱা কামৰ বাবে ভাল সময়।",
        "mi_role_student": "শ্ৰেণীৰ বাবে সদায়তকৈ সোনকালে ওলোৱাৰ কথা ভাবক।",
        "mi_role_student_calm": "যাত্ৰাৰ বাবে পৰিষ্কাৰ সময়।",
        "mi_role_caregiver": "সোনকালে লৰচৰ কৰিব নোৱাৰাসকলৰ খবৰ লোৱাৰ কথা ভাবক।",
        "mi_role_caregiver_calm": "বাহিৰত লগ ধৰিবলৈ শান্ত সময়।",
    },
}

for _lang, _extra in ROLE_SENTENCES_EXTRA.items():
    ROLE_SENTENCES.setdefault(_lang, {}).update(_extra)


# The twelve-role brief added five more readers: a researcher, a disaster
# manager, an aviation professional, a government official and an event planner.
# Same reasoning as the table above — kept in its own block so a missing
# translation is a visible hole rather than a silent English fallback.
#
# Only headings and one disclosure are new. Every *card* these five readers see
# is an existing card, in an existing translation: what differs is which cards
# they get, in what order, and which measurements lead. A role that invented its
# own vocabulary would be a role whose wording nobody had checked.
ROLE_SENTENCES_ROLES_12: dict[str, dict[str, str]] = {
    # -----------------------------------------------------------------------
    "en": {
        "ri_heading_researcher": 'Measurement and trend intelligence',
        "ri_heading_disaster_manager": 'Response and preparedness intelligence',
        "ri_heading_aviation": 'Aviation surface intelligence',
        "ri_heading_government": 'Civic weather intelligence',
        "ri_heading_event_planner": 'Event-day intelligence',
        "ri_note_aviation": 'Aviation products are not available in this app — no METAR, TAF, cloud base, icing or turbulence data. This reading uses surface wind, visibility, pressure and storm risk from the general forecast.',
    },
    # -----------------------------------------------------------------------
    "hi": {
        "ri_heading_researcher": 'माप और रुझान की मौसम जानकारी',
        "ri_heading_disaster_manager": 'आपदा प्रतिक्रिया और तैयारी की जानकारी',
        "ri_heading_aviation": 'विमानन सतही मौसम जानकारी',
        "ri_heading_government": 'नागरिक सेवाओं की मौसम जानकारी',
        "ri_heading_event_planner": 'आयोजन के दिन की मौसम जानकारी',
        "ri_note_aviation": 'इस ऐप में विमानन उत्पाद उपलब्ध नहीं हैं — METAR, TAF, बादल की ऊँचाई, हिमीकरण या अशांति का डेटा नहीं है। यह पाठ सामान्य पूर्वानुमान से सतही हवा, दृश्यता, दाब और तूफ़ान जोखिम का उपयोग करता है।',
    },
    # -----------------------------------------------------------------------
    "te": {
        "ri_heading_researcher": 'కొలతలు, ధోరణుల వాతావరణ సమాచారం',
        "ri_heading_disaster_manager": 'విపత్తు స్పందన, సన్నద్ధత సమాచారం',
        "ri_heading_aviation": 'విమానయాన ఉపరితల వాతావరణ సమాచారం',
        "ri_heading_government": 'పౌర సేవల వాతావరణ సమాచారం',
        "ri_heading_event_planner": 'కార్యక్రమ దినపు వాతావరణ సమాచారం',
        "ri_note_aviation": 'ఈ యాప్\u200cలో విమానయాన ఉత్పత్తులు అందుబాటులో లేవు — METAR, TAF, మేఘాల ఎత్తు, మంచు పేరుకోవడం లేదా అల్లకల్లోల సమాచారం లేదు. ఇది సాధారణ సూచన నుండి ఉపరితల గాలి, దృశ్యత, పీడనం, తుఫాను ప్రమాదాన్ని ఉపయోగిస్తుంది.',
    },
    # -----------------------------------------------------------------------
    "bn": {
        "ri_heading_researcher": 'পরিমাপ ও প্রবণতার আবহাওয়া তথ্য',
        "ri_heading_disaster_manager": 'দুর্যোগ সাড়া ও প্রস্তুতির তথ্য',
        "ri_heading_aviation": 'বিমান চলাচলের ভূপৃষ্ঠ আবহাওয়া তথ্য',
        "ri_heading_government": 'নাগরিক পরিষেবার আবহাওয়া তথ্য',
        "ri_heading_event_planner": 'অনুষ্ঠানের দিনের আবহাওয়া তথ্য',
        "ri_note_aviation": 'এই অ্যাপে বিমান চলাচলের পণ্য নেই — METAR, TAF, মেঘের উচ্চতা, বরফ জমা বা ঝাঁকুনির তথ্য নেই। এই পাঠটি সাধারণ পূর্বাভাস থেকে ভূপৃষ্ঠের বাতাস, দৃশ্যমানতা, চাপ ও ঝড়ের ঝুঁকি ব্যবহার করে।',
    },
    # -----------------------------------------------------------------------
    "mr": {
        "ri_heading_researcher": 'मापन आणि कल यांची हवामान माहिती',
        "ri_heading_disaster_manager": 'आपत्ती प्रतिसाद व सज्जतेची माहिती',
        "ri_heading_aviation": 'विमान वाहतुकीची भूपृष्ठ हवामान माहिती',
        "ri_heading_government": 'नागरी सेवांची हवामान माहिती',
        "ri_heading_event_planner": 'कार्यक्रमाच्या दिवसाची हवामान माहिती',
        "ri_note_aviation": 'या अॅपमध्ये विमान वाहतुकीची उत्पादने उपलब्ध नाहीत — METAR, TAF, ढगांची उंची, बर्फ साचणे किंवा हादऱ्यांची माहिती नाही. हे वाचन सर्वसाधारण अंदाजातील भूपृष्ठावरील वारा, दृश्यमानता, दाब आणि वादळाचा धोका वापरते.',
    },
    # -----------------------------------------------------------------------
    "as": {
        "ri_heading_researcher": 'জোখ-মাপ আৰু ধাৰাৰ বতৰ তথ্য',
        "ri_heading_disaster_manager": 'দুৰ্যোগ সঁহাৰি আৰু প্ৰস্তুতিৰ তথ্য',
        "ri_heading_aviation": 'বিমান চলাচলৰ ভূপৃষ্ঠ বতৰ তথ্য',
        "ri_heading_government": 'নাগৰিক সেৱাৰ বতৰ তথ্য',
        "ri_heading_event_planner": 'অনুষ্ঠানৰ দিনৰ বতৰ তথ্য',
        "ri_note_aviation": 'এই এপত বিমান চলাচলৰ সামগ্ৰী নাই — METAR, TAF, ডাৱৰৰ উচ্চতা, বৰফ জমা হোৱা বা জোকাৰণিৰ তথ্য নাই। এই পঠনে সাধাৰণ পূৰ্বাভাসৰ পৰা ভূপৃষ্ঠৰ বতাহ, দৃশ্যমানতা, চাপ আৰু ধুমুহাৰ ঝুঁকি ব্যৱহাৰ কৰে।',
    },
}

for _lang, _extra in ROLE_SENTENCES_ROLES_12.items():
    ROLE_SENTENCES.setdefault(_lang, {}).update(_extra)
